// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: common/ip-transport.proto

package common

import (
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IP Anddress family
type IpAddrFamily int32

const (
	IpAddrFamily__    IpAddrFamily = 0
	IpAddrFamily_IPv4 IpAddrFamily = 1 //IPv4
	IpAddrFamily_IPv6 IpAddrFamily = 2 //IPv6
)

// Enum value maps for IpAddrFamily.
var (
	IpAddrFamily_name = map[int32]string{
		0: "_",
		1: "IPv4",
		2: "IPv6",
	}
	IpAddrFamily_value = map[string]int32{
		"_":    0,
		"IPv4": 1,
		"IPv6": 2,
	}
)

func (x IpAddrFamily) Enum() *IpAddrFamily {
	p := new(IpAddrFamily)
	*p = x
	return p
}

func (x IpAddrFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpAddrFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[0].Descriptor()
}

func (IpAddrFamily) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[0]
}

func (x IpAddrFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpAddrFamily.Descriptor instead.
func (IpAddrFamily) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0}
}

// Ingress / Egress traffic dir
type Traffic int32

const (
	Traffic_Undef   Traffic = 0 // undefined tfaffic direction
	Traffic_Ingress Traffic = 1 // Ingress
	Traffic_Egress  Traffic = 2 // Egress
)

// Enum value maps for Traffic.
var (
	Traffic_name = map[int32]string{
		0: "Undef",
		1: "Ingress",
		2: "Egress",
	}
	Traffic_value = map[string]int32{
		"Undef":   0,
		"Ingress": 1,
		"Egress":  2,
	}
)

func (x Traffic) Enum() *Traffic {
	p := new(Traffic)
	*p = x
	return p
}

func (x Traffic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Traffic) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[1].Descriptor()
}

func (Traffic) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[1]
}

func (x Traffic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Traffic.Descriptor instead.
func (Traffic) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{1}
}

// Transport: represents net transport (L4)
type Networks_NetIP_Transport int32

const (
	Networks_NetIP_TCP Networks_NetIP_Transport = 0
	Networks_NetIP_UDP Networks_NetIP_Transport = 1
)

// Enum value maps for Networks_NetIP_Transport.
var (
	Networks_NetIP_Transport_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	Networks_NetIP_Transport_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x Networks_NetIP_Transport) Enum() *Networks_NetIP_Transport {
	p := new(Networks_NetIP_Transport)
	*p = x
	return p
}

func (x Networks_NetIP_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Networks_NetIP_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[2].Descriptor()
}

func (Networks_NetIP_Transport) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[2]
}

func (x Networks_NetIP_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Networks_NetIP_Transport.Descriptor instead.
func (Networks_NetIP_Transport) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0, 0}
}

// Networks: represents network types
type Networks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Networks) Reset() {
	*x = Networks{}
	mi := &file_common_ip_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Networks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Networks) ProtoMessage() {}

func (x *Networks) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Networks.ProtoReflect.Descriptor instead.
func (*Networks) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0}
}

// IP/ICMP protocol
type ICMP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPv           IpAddrFamily           `protobuf:"varint,1,opt,name=IPv,proto3,enum=common.IpAddrFamily" json:"IPv,omitempty"`
	Types         []uint32               `protobuf:"varint,2,rep,packed,name=Types,proto3" json:"Types,omitempty"` // ICMP message types
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICMP) Reset() {
	*x = ICMP{}
	mi := &file_common_ip_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICMP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICMP) ProtoMessage() {}

func (x *ICMP) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICMP.ProtoReflect.Descriptor instead.
func (*ICMP) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{1}
}

func (x *ICMP) GetIPv() IpAddrFamily {
	if x != nil {
		return x.IPv
	}
	return IpAddrFamily__
}

func (x *ICMP) GetTypes() []uint32 {
	if x != nil {
		return x.Types
	}
	return nil
}

// NetIP: represents IP-Network type (L3)
type Networks_NetIP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CIDR: IP range
	CIDR          string `protobuf:"bytes,1,opt,name=CIDR,proto3" json:"CIDR,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Networks_NetIP) Reset() {
	*x = Networks_NetIP{}
	mi := &file_common_ip_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Networks_NetIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Networks_NetIP) ProtoMessage() {}

func (x *Networks_NetIP) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Networks_NetIP.ProtoReflect.Descriptor instead.
func (*Networks_NetIP) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Networks_NetIP) GetCIDR() string {
	if x != nil {
		return x.CIDR
	}
	return ""
}

// PortRange: port [from - to] range
type Networks_NetIP_PortRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// range left bound
	From uint32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// range right bound
	To            uint32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Networks_NetIP_PortRange) Reset() {
	*x = Networks_NetIP_PortRange{}
	mi := &file_common_ip_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Networks_NetIP_PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Networks_NetIP_PortRange) ProtoMessage() {}

func (x *Networks_NetIP_PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Networks_NetIP_PortRange.ProtoReflect.Descriptor instead.
func (*Networks_NetIP_PortRange) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Networks_NetIP_PortRange) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Networks_NetIP_PortRange) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_common_ip_transport_proto protoreflect.FileDescriptor

const file_common_ip_transport_proto_rawDesc = "" +
	"\n" +
	"\x19common/ip-transport.proto\x12\x06common\x1a google/protobuf/descriptor.proto\"w\n" +
	"\bNetworks\x1ak\n" +
	"\x05NetIP\x12\x12\n" +
	"\x04CIDR\x18\x01 \x01(\tR\x04CIDR\x1a/\n" +
	"\tPortRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\rR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\rR\x02to\"\x1d\n" +
	"\tTransport\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\"D\n" +
	"\x04ICMP\x12&\n" +
	"\x03IPv\x18\x01 \x01(\x0e2\x14.common.IpAddrFamilyR\x03IPv\x12\x14\n" +
	"\x05Types\x18\x02 \x03(\rR\x05Types*)\n" +
	"\fIpAddrFamily\x12\x05\n" +
	"\x01_\x10\x00\x12\b\n" +
	"\x04IPv4\x10\x01\x12\b\n" +
	"\x04IPv6\x10\x02*-\n" +
	"\aTraffic\x12\t\n" +
	"\x05Undef\x10\x00\x12\v\n" +
	"\aIngress\x10\x01\x12\n" +
	"\n" +
	"\x06Egress\x10\x02B6Z4github.com/PRO-Robotech/protos/pkg/api/common;commonb\x06proto3"

var (
	file_common_ip_transport_proto_rawDescOnce sync.Once
	file_common_ip_transport_proto_rawDescData []byte
)

func file_common_ip_transport_proto_rawDescGZIP() []byte {
	file_common_ip_transport_proto_rawDescOnce.Do(func() {
		file_common_ip_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_ip_transport_proto_rawDesc), len(file_common_ip_transport_proto_rawDesc)))
	})
	return file_common_ip_transport_proto_rawDescData
}

var file_common_ip_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_ip_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_ip_transport_proto_goTypes = []any{
	(IpAddrFamily)(0),                // 0: common.IpAddrFamily
	(Traffic)(0),                     // 1: common.Traffic
	(Networks_NetIP_Transport)(0),    // 2: common.Networks.NetIP.Transport
	(*Networks)(nil),                 // 3: common.Networks
	(*ICMP)(nil),                     // 4: common.ICMP
	(*Networks_NetIP)(nil),           // 5: common.Networks.NetIP
	(*Networks_NetIP_PortRange)(nil), // 6: common.Networks.NetIP.PortRange
}
var file_common_ip_transport_proto_depIdxs = []int32{
	0, // 0: common.ICMP.IPv:type_name -> common.IpAddrFamily
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_ip_transport_proto_init() }
func file_common_ip_transport_proto_init() {
	if File_common_ip_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_ip_transport_proto_rawDesc), len(file_common_ip_transport_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_ip_transport_proto_goTypes,
		DependencyIndexes: file_common_ip_transport_proto_depIdxs,
		EnumInfos:         file_common_ip_transport_proto_enumTypes,
		MessageInfos:      file_common_ip_transport_proto_msgTypes,
	}.Build()
	File_common_ip_transport_proto = out.File
	file_common_ip_transport_proto_goTypes = nil
	file_common_ip_transport_proto_depIdxs = nil
}
