// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: agent/v1/messages.proto

package agentv1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Authentication data
type SecretData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64-encoded plain value
	RawValue string `protobuf:"bytes,1,opt,name=raw_value,json=rawValue,proto3" json:"raw_value,omitempty"`
	// Base64-encoded encrypted value: BASE64(IV(16 bytes) + ciphertext)
	SecureValue   string `protobuf:"bytes,2,opt,name=secure_value,json=secureValue,proto3" json:"secure_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretData) Reset() {
	*x = SecretData{}
	mi := &file_agent_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretData) ProtoMessage() {}

func (x *SecretData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretData.ProtoReflect.Descriptor instead.
func (*SecretData) Descriptor() ([]byte, []int) {
	return file_agent_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SecretData) GetRawValue() string {
	if x != nil {
		return x.RawValue
	}
	return ""
}

func (x *SecretData) GetSecureValue() string {
	if x != nil {
		return x.SecureValue
	}
	return ""
}

// Methods for ownership verification
type OwnerCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Auth:
	//
	//	*OwnerCheck_NoAuth
	//	*OwnerCheck_Secret
	Auth          isOwnerCheck_Auth `protobuf_oneof:"auth"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerCheck) Reset() {
	*x = OwnerCheck{}
	mi := &file_agent_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerCheck) ProtoMessage() {}

func (x *OwnerCheck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerCheck.ProtoReflect.Descriptor instead.
func (*OwnerCheck) Descriptor() ([]byte, []int) {
	return file_agent_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *OwnerCheck) GetAuth() isOwnerCheck_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *OwnerCheck) GetNoAuth() *empty.Empty {
	if x != nil {
		if x, ok := x.Auth.(*OwnerCheck_NoAuth); ok {
			return x.NoAuth
		}
	}
	return nil
}

func (x *OwnerCheck) GetSecret() *SecretData {
	if x != nil {
		if x, ok := x.Auth.(*OwnerCheck_Secret); ok {
			return x.Secret
		}
	}
	return nil
}

type isOwnerCheck_Auth interface {
	isOwnerCheck_Auth()
}

type OwnerCheck_NoAuth struct {
	NoAuth *empty.Empty `protobuf:"bytes,1,opt,name=no_auth,json=noAuth,proto3,oneof"`
}

type OwnerCheck_Secret struct {
	Secret *SecretData `protobuf:"bytes,2,opt,name=secret,proto3,oneof"`
}

func (*OwnerCheck_NoAuth) isOwnerCheck_Auth() {}

func (*OwnerCheck_Secret) isOwnerCheck_Auth() {}

// Basic registration details
type RegInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegInfo) Reset() {
	*x = RegInfo{}
	mi := &file_agent_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegInfo) ProtoMessage() {}

func (x *RegInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegInfo.ProtoReflect.Descriptor instead.
func (*RegInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RegInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RegInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Registration info request with ownership check
type RegInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *OwnerCheck            `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegInfoReq) Reset() {
	*x = RegInfoReq{}
	mi := &file_agent_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegInfoReq) ProtoMessage() {}

func (x *RegInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegInfoReq.ProtoReflect.Descriptor instead.
func (*RegInfoReq) Descriptor() ([]byte, []int) {
	return file_agent_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RegInfoReq) GetCondition() *OwnerCheck {
	if x != nil {
		return x.Condition
	}
	return nil
}

var File_agent_v1_messages_proto protoreflect.FileDescriptor

const file_agent_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x17agent/v1/messages.proto\x12\fhbf.v1.agent\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"L\n" +
	"\n" +
	"SecretData\x12\x1b\n" +
	"\traw_value\x18\x01 \x01(\tR\brawValue\x12!\n" +
	"\fsecure_value\x18\x02 \x01(\tR\vsecureValue\"{\n" +
	"\n" +
	"OwnerCheck\x121\n" +
	"\ano_auth\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06noAuth\x122\n" +
	"\x06secret\x18\x02 \x01(\v2\x18.hbf.v1.agent.SecretDataH\x00R\x06secretB\x06\n" +
	"\x04auth\"\x81\x03\n" +
	"\aRegInfo\x12t\n" +
	"\x04uuid\x18\x01 \x01(\tB`\x92A]*\x04uuid2 host uuid (up to 255 characters)J&\"2438ac3c-37eb-4902-adef-ed16b4431030\"\x8a\x01\n" +
	"^.{1,255}$R\x04uuid\x12\xb5\x01\n" +
	"\x04name\x18\x02 \x01(\tB\xa0\x01\x92A\x9c\x01*\bhostname2\x13DNS-style host nameJ\x19\"my-server01.example.com\"\x8a\x01_^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$R\x04name:H\x92AE\n" +
	"C*\aRegInfo28RegInfo - response with basic agent registration details\"\x8a\x02\n" +
	"\n" +
	"RegInfoReq\x12|\n" +
	"\tcondition\x18\x01 \x01(\v2\x18.hbf.v1.agent.OwnerCheckBD\x92AA*\tcondition24Ownership verification method (empty or secret data)R\tcondition:~\x92A{\n" +
	"y*\x17RegistrationInfoRequest2RRequest object for fetching registration info with optional ownership verification\xd2\x01\tconditionB9Z7github.com/PRO-Robotech/protos/pkg/api/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_messages_proto_rawDescOnce sync.Once
	file_agent_v1_messages_proto_rawDescData []byte
)

func file_agent_v1_messages_proto_rawDescGZIP() []byte {
	file_agent_v1_messages_proto_rawDescOnce.Do(func() {
		file_agent_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_messages_proto_rawDesc), len(file_agent_v1_messages_proto_rawDesc)))
	})
	return file_agent_v1_messages_proto_rawDescData
}

var file_agent_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_v1_messages_proto_goTypes = []any{
	(*SecretData)(nil),  // 0: hbf.v1.agent.SecretData
	(*OwnerCheck)(nil),  // 1: hbf.v1.agent.OwnerCheck
	(*RegInfo)(nil),     // 2: hbf.v1.agent.RegInfo
	(*RegInfoReq)(nil),  // 3: hbf.v1.agent.RegInfoReq
	(*empty.Empty)(nil), // 4: google.protobuf.Empty
}
var file_agent_v1_messages_proto_depIdxs = []int32{
	4, // 0: hbf.v1.agent.OwnerCheck.no_auth:type_name -> google.protobuf.Empty
	0, // 1: hbf.v1.agent.OwnerCheck.secret:type_name -> hbf.v1.agent.SecretData
	1, // 2: hbf.v1.agent.RegInfoReq.condition:type_name -> hbf.v1.agent.OwnerCheck
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_v1_messages_proto_init() }
func file_agent_v1_messages_proto_init() {
	if File_agent_v1_messages_proto != nil {
		return
	}
	file_agent_v1_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*OwnerCheck_NoAuth)(nil),
		(*OwnerCheck_Secret)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_messages_proto_rawDesc), len(file_agent_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_messages_proto_goTypes,
		DependencyIndexes: file_agent_v1_messages_proto_depIdxs,
		MessageInfos:      file_agent_v1_messages_proto_msgTypes,
	}.Build()
	File_agent_v1_messages_proto = out.File
	file_agent_v1_messages_proto_goTypes = nil
	file_agent_v1_messages_proto_depIdxs = nil
}
