// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: agent/v1/service.proto

package agentv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_agent_v1_service_proto protoreflect.FileDescriptor

const file_agent_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16agent/v1/service.proto\x12\fhbf.v1.agent\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17agent/v1/messages.proto2\xe9\x01\n" +
	"\fAgentService\x12\xb0\x01\n" +
	"\x14GetAgentRegistration\x12\x18.hbf.v1.agent.RegInfoReq\x1a\x15.hbf.v1.agent.RegInfo\"g\x92AI\x1aGGetAgentRegistration: returns basic registration details from the agent\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/registration\x1a&\x92A#\x12!Security Groups Agent API serviceB\x85\x01\x92AI\x12 \n" +
	"\x19Security Groups Agent API2\x031.0*\x01\x012\x10application/json:\x10application/jsonZ7github.com/PRO-Robotech/protos/pkg/api/agent/v1;agentv1b\x06proto3"

var file_agent_v1_service_proto_goTypes = []any{
	(*RegInfoReq)(nil), // 0: hbf.v1.agent.RegInfoReq
	(*RegInfo)(nil),    // 1: hbf.v1.agent.RegInfo
}
var file_agent_v1_service_proto_depIdxs = []int32{
	0, // 0: hbf.v1.agent.AgentService.GetAgentRegistration:input_type -> hbf.v1.agent.RegInfoReq
	1, // 1: hbf.v1.agent.AgentService.GetAgentRegistration:output_type -> hbf.v1.agent.RegInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_v1_service_proto_init() }
func file_agent_v1_service_proto_init() {
	if File_agent_v1_service_proto != nil {
		return
	}
	file_agent_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_service_proto_rawDesc), len(file_agent_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_service_proto_goTypes,
		DependencyIndexes: file_agent_v1_service_proto_depIdxs,
	}.Build()
	File_agent_v1_service_proto = out.File
	file_agent_v1_service_proto_goTypes = nil
	file_agent_v1_service_proto_depIdxs = nil
}
