// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: sgroups/domains.proto

package sgroups

import (
	common "github.com/PRO-Robotech/protos/pkg/api/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleAction: represents verdict action for rules
type RuleAction int32

const (
	// Undefined verdict action
	RuleAction_UNDEF RuleAction = 0
	// Drops net packet
	RuleAction_DROP RuleAction = 1
	// Accepts net packet
	RuleAction_ACCEPT RuleAction = 2
)

// Enum value maps for RuleAction.
var (
	RuleAction_name = map[int32]string{
		0: "UNDEF",
		1: "DROP",
		2: "ACCEPT",
	}
	RuleAction_value = map[string]int32{
		"UNDEF":  0,
		"DROP":   1,
		"ACCEPT": 2,
	}
)

func (x RuleAction) Enum() *RuleAction {
	p := new(RuleAction)
	*p = x
	return p
}

func (x RuleAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleAction) Descriptor() protoreflect.EnumDescriptor {
	return file_sgroups_domains_proto_enumTypes[0].Descriptor()
}

func (RuleAction) Type() protoreflect.EnumType {
	return &file_sgroups_domains_proto_enumTypes[0]
}

func (x RuleAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleAction.Descriptor instead.
func (RuleAction) EnumDescriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{0}
}

// DefaultAction: represents default action at end of chains for Security Gpoup
type SecGroup_DefaultAction int32

const (
	// Default is default action in [DROP|ACCEPT]
	SecGroup_DEFAULT SecGroup_DefaultAction = 0
	// Drops net packet
	SecGroup_DROP SecGroup_DefaultAction = 1
	// Accepts net packet
	SecGroup_ACCEPT SecGroup_DefaultAction = 2
)

// Enum value maps for SecGroup_DefaultAction.
var (
	SecGroup_DefaultAction_name = map[int32]string{
		0: "DEFAULT",
		1: "DROP",
		2: "ACCEPT",
	}
	SecGroup_DefaultAction_value = map[string]int32{
		"DEFAULT": 0,
		"DROP":    1,
		"ACCEPT":  2,
	}
)

func (x SecGroup_DefaultAction) Enum() *SecGroup_DefaultAction {
	p := new(SecGroup_DefaultAction)
	*p = x
	return p
}

func (x SecGroup_DefaultAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecGroup_DefaultAction) Descriptor() protoreflect.EnumDescriptor {
	return file_sgroups_domains_proto_enumTypes[1].Descriptor()
}

func (SecGroup_DefaultAction) Type() protoreflect.EnumType {
	return &file_sgroups_domains_proto_enumTypes[1]
}

func (x SecGroup_DefaultAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecGroup_DefaultAction.Descriptor instead.
func (SecGroup_DefaultAction) EnumDescriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{3, 0}
}

// AccPorts: represents Security Group Rule access source-dest ports
type AccPorts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source port "num" or port range "num1-num2"
	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	// destination  port "num" or port range "num1-num2"
	D             string `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccPorts) Reset() {
	*x = AccPorts{}
	mi := &file_sgroups_domains_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccPorts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccPorts) ProtoMessage() {}

func (x *AccPorts) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccPorts.ProtoReflect.Descriptor instead.
func (*AccPorts) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{0}
}

func (x *AccPorts) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *AccPorts) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

// RulePriority: represents rule priority or none if we no need use it
type RulePriority struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*RulePriority_Some
	Value         isRulePriority_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulePriority) Reset() {
	*x = RulePriority{}
	mi := &file_sgroups_domains_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulePriority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulePriority) ProtoMessage() {}

func (x *RulePriority) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulePriority.ProtoReflect.Descriptor instead.
func (*RulePriority) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{1}
}

func (x *RulePriority) GetValue() isRulePriority_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RulePriority) GetSome() int32 {
	if x != nil {
		if x, ok := x.Value.(*RulePriority_Some); ok {
			return x.Some
		}
	}
	return 0
}

type isRulePriority_Value interface {
	isRulePriority_Value()
}

type RulePriority_Some struct {
	Some int32 `protobuf:"varint,1,opt,name=some,proto3,oneof"`
}

func (*RulePriority_Some) isRulePriority_Value() {}

// Network: represents a named IP network
type Network struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of network
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// network in CIDR form
	Network       *common.Networks_NetIP `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_sgroups_domains_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{2}
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetNetwork() *common.Networks_NetIP {
	if x != nil {
		return x.Network
	}
	return nil
}

// SecGroup: represents a security group
type SecGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of security group
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// related to security gpoup network(s)
	Networks []string `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty"`
	// default_action: represents default rule action
	DefaultAction SecGroup_DefaultAction `protobuf:"varint,3,opt,name=default_action,json=defaultAction,proto3,enum=hbf.v2.sgroups.SecGroup_DefaultAction" json:"default_action,omitempty"`
	// trace: set or unset 'nftrace' flag
	Trace bool `protobuf:"varint,4,opt,name=trace,proto3" json:"trace,omitempty"`
	// logs: switch-{ON|OFF} logs in chain
	Logs bool `protobuf:"varint,5,opt,name=logs,proto3" json:"logs,omitempty"`
	// host: related to security group host names
	Hosts []string `protobuf:"bytes,6,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// services: related to security group service names
	Services      []string `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecGroup) Reset() {
	*x = SecGroup{}
	mi := &file_sgroups_domains_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecGroup) ProtoMessage() {}

func (x *SecGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecGroup.ProtoReflect.Descriptor instead.
func (*SecGroup) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{3}
}

func (x *SecGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecGroup) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *SecGroup) GetDefaultAction() SecGroup_DefaultAction {
	if x != nil {
		return x.DefaultAction
	}
	return SecGroup_DEFAULT
}

func (x *SecGroup) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *SecGroup) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *SecGroup) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *SecGroup) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// IPList : list of hosts IPs
type IPList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPs           []string               `protobuf:"bytes,1,rep,name=IPs,proto3" json:"IPs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPList) Reset() {
	*x = IPList{}
	mi := &file_sgroups_domains_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPList) ProtoMessage() {}

func (x *IPList) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPList.ProtoReflect.Descriptor instead.
func (*IPList) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{4}
}

func (x *IPList) GetIPs() []string {
	if x != nil {
		return x.IPs
	}
	return nil
}

// Host: represents a host with its name, UUID, and IPs related to Security Group(s)
type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SgName        string                 `protobuf:"bytes,3,opt,name=sg_name,json=sgName,proto3" json:"sg_name,omitempty"`
	IpList        *IPList                `protobuf:"bytes,4,opt,name=ip_list,json=ipList,proto3" json:"ip_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_sgroups_domains_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{5}
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Host) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Host) GetSgName() string {
	if x != nil {
		return x.SgName
	}
	return ""
}

func (x *Host) GetIpList() *IPList {
	if x != nil {
		return x.IpList
	}
	return nil
}

// HostIPSet: represents a set of IPs for a host
type HostIPSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	IpList        *IPList                `protobuf:"bytes,2,opt,name=ip_list,json=ipList,proto3" json:"ip_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostIPSet) Reset() {
	*x = HostIPSet{}
	mi := &file_sgroups_domains_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostIPSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostIPSet) ProtoMessage() {}

func (x *HostIPSet) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostIPSet.ProtoReflect.Descriptor instead.
func (*HostIPSet) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{6}
}

func (x *HostIPSet) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HostIPSet) GetIpList() *IPList {
	if x != nil {
		return x.IpList
	}
	return nil
}

// ProtoSpec: represents protocols specification (ports, icmp types)
type ProtoSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tcp ports
	Tcp *ProtoSpec_Ports `protobuf:"bytes,1,opt,name=tcp,proto3" json:"tcp,omitempty"`
	// udp ports
	Udp *ProtoSpec_Ports `protobuf:"bytes,2,opt,name=udp,proto3" json:"udp,omitempty"`
	// icmpv4 types
	Icmpv4 *ProtoSpec_IcmpTypes `protobuf:"bytes,3,opt,name=icmpv4,proto3" json:"icmpv4,omitempty"`
	// icmpv6 types
	Icmpv6        *ProtoSpec_IcmpTypes `protobuf:"bytes,4,opt,name=icmpv6,proto3" json:"icmpv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSpec) Reset() {
	*x = ProtoSpec{}
	mi := &file_sgroups_domains_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSpec) ProtoMessage() {}

func (x *ProtoSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSpec.ProtoReflect.Descriptor instead.
func (*ProtoSpec) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoSpec) GetTcp() *ProtoSpec_Ports {
	if x != nil {
		return x.Tcp
	}
	return nil
}

func (x *ProtoSpec) GetUdp() *ProtoSpec_Ports {
	if x != nil {
		return x.Udp
	}
	return nil
}

func (x *ProtoSpec) GetIcmpv4() *ProtoSpec_IcmpTypes {
	if x != nil {
		return x.Icmpv4
	}
	return nil
}

func (x *ProtoSpec) GetIcmpv6() *ProtoSpec_IcmpTypes {
	if x != nil {
		return x.Icmpv6
	}
	return nil
}

// Service: represents a service resource
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of service
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// protocols specification (ports, icmp types)
	Protocols *ProtoSpec `protobuf:"bytes,2,opt,name=protocols,proto3" json:"protocols,omitempty"`
	// related to security group name(s)
	SgNames       []string `protobuf:"bytes,3,rep,name=sg_names,json=sgNames,proto3" json:"sg_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_sgroups_domains_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{8}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetProtocols() *ProtoSpec {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Service) GetSgNames() []string {
	if x != nil {
		return x.SgNames
	}
	return nil
}

// SvcSvcRule: represents Service-to-Service Rule
type SvcSvcRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rule name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// service at client
	SvcFrom string `protobuf:"bytes,2,opt,name=svc_from,json=svcFrom,proto3" json:"svc_from,omitempty"`
	// service at server
	SvcTo string `protobuf:"bytes,3,opt,name=svc_to,json=svcTo,proto3" json:"svc_to,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,4,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority *RulePriority `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,6,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} trace in rules
	Trace         bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SvcSvcRule) Reset() {
	*x = SvcSvcRule{}
	mi := &file_sgroups_domains_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SvcSvcRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcSvcRule) ProtoMessage() {}

func (x *SvcSvcRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcSvcRule.ProtoReflect.Descriptor instead.
func (*SvcSvcRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{9}
}

func (x *SvcSvcRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SvcSvcRule) GetSvcFrom() string {
	if x != nil {
		return x.SvcFrom
	}
	return ""
}

func (x *SvcSvcRule) GetSvcTo() string {
	if x != nil {
		return x.SvcTo
	}
	return ""
}

func (x *SvcSvcRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *SvcSvcRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *SvcSvcRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *SvcSvcRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

// SgSgRule: represents Security Groups Rule
type SgSgRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// security group at client
	SgFrom string `protobuf:"bytes,1,opt,name=sg_from,json=sgFrom,proto3" json:"sg_from,omitempty"`
	// security group at server
	SgTo string `protobuf:"bytes,2,opt,name=sg_to,json=sgTo,proto3" json:"sg_to,omitempty"`
	// ip net transport
	Transport common.Networks_NetIP_Transport `protobuf:"varint,3,opt,name=transport,proto3,enum=common.Networks_NetIP_Transport" json:"transport,omitempty"`
	// access ports set
	Ports []*AccPorts `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,5,opt,name=logs,proto3" json:"logs,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,6,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SgSgRule) Reset() {
	*x = SgSgRule{}
	mi := &file_sgroups_domains_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SgSgRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SgSgRule) ProtoMessage() {}

func (x *SgSgRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SgSgRule.ProtoReflect.Descriptor instead.
func (*SgSgRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{10}
}

func (x *SgSgRule) GetSgFrom() string {
	if x != nil {
		return x.SgFrom
	}
	return ""
}

func (x *SgSgRule) GetSgTo() string {
	if x != nil {
		return x.SgTo
	}
	return ""
}

func (x *SgSgRule) GetTransport() common.Networks_NetIP_Transport {
	if x != nil {
		return x.Transport
	}
	return common.Networks_NetIP_Transport(0)
}

func (x *SgSgRule) GetPorts() []*AccPorts {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *SgSgRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *SgSgRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *SgSgRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

// FqdnRule: represents Security Groups Rule
type FqdnRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// security group at client
	SgFrom string `protobuf:"bytes,1,opt,name=sg_from,json=sgFrom,proto3" json:"sg_from,omitempty"`
	// FQDN full qualified domain name portable for DNS queries
	FQDN string `protobuf:"bytes,2,opt,name=FQDN,proto3" json:"FQDN,omitempty"`
	// ip net transport
	Transport common.Networks_NetIP_Transport `protobuf:"varint,3,opt,name=transport,proto3,enum=common.Networks_NetIP_Transport" json:"transport,omitempty"`
	// access ports set
	Ports []*AccPorts `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,5,opt,name=logs,proto3" json:"logs,omitempty"`
	// protocols: L7 protocol list
	// repeated string protocols = 6;
	// action: represents rule action
	Action RuleAction `protobuf:"varint,7,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FqdnRule) Reset() {
	*x = FqdnRule{}
	mi := &file_sgroups_domains_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FqdnRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FqdnRule) ProtoMessage() {}

func (x *FqdnRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FqdnRule.ProtoReflect.Descriptor instead.
func (*FqdnRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{11}
}

func (x *FqdnRule) GetSgFrom() string {
	if x != nil {
		return x.SgFrom
	}
	return ""
}

func (x *FqdnRule) GetFQDN() string {
	if x != nil {
		return x.FQDN
	}
	return ""
}

func (x *FqdnRule) GetTransport() common.Networks_NetIP_Transport {
	if x != nil {
		return x.Transport
	}
	return common.Networks_NetIP_Transport(0)
}

func (x *FqdnRule) GetPorts() []*AccPorts {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *FqdnRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *FqdnRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *FqdnRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

// SvcFqdnRule: represents Service to FQDN Rule
type SvcFqdnRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rule name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// service at client
	SvcFrom string `protobuf:"bytes,2,opt,name=svc_from,json=svcFrom,proto3" json:"svc_from,omitempty"`
	// FQDN full qualified domain name portable for DNS queries
	FQDN string `protobuf:"bytes,3,opt,name=FQDN,proto3" json:"FQDN,omitempty"`
	// ip net transport
	Transport common.Networks_NetIP_Transport `protobuf:"varint,4,opt,name=transport,proto3,enum=common.Networks_NetIP_Transport" json:"transport,omitempty"`
	// access ports set
	Ports []*AccPorts `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,6,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} trace in rules
	Trace bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,8,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,9,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SvcFqdnRule) Reset() {
	*x = SvcFqdnRule{}
	mi := &file_sgroups_domains_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SvcFqdnRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcFqdnRule) ProtoMessage() {}

func (x *SvcFqdnRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcFqdnRule.ProtoReflect.Descriptor instead.
func (*SvcFqdnRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{12}
}

func (x *SvcFqdnRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SvcFqdnRule) GetSvcFrom() string {
	if x != nil {
		return x.SvcFrom
	}
	return ""
}

func (x *SvcFqdnRule) GetFQDN() string {
	if x != nil {
		return x.FQDN
	}
	return ""
}

func (x *SvcFqdnRule) GetTransport() common.Networks_NetIP_Transport {
	if x != nil {
		return x.Transport
	}
	return common.Networks_NetIP_Transport(0)
}

func (x *SvcFqdnRule) GetPorts() []*AccPorts {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *SvcFqdnRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *SvcFqdnRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *SvcFqdnRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *SvcFqdnRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

// SG:ICMP type rule
type SgIcmpRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security group name
	SG string `protobuf:"bytes,1,opt,name=SG,proto3" json:"SG,omitempty"`
	// ICMP spec
	ICMP *common.ICMP `protobuf:"bytes,2,opt,name=ICMP,proto3" json:"ICMP,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,3,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} trace in rules
	Trace bool `protobuf:"varint,4,opt,name=trace,proto3" json:"trace,omitempty"`
	// action: represents rule action
	Action        RuleAction `protobuf:"varint,5,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SgIcmpRule) Reset() {
	*x = SgIcmpRule{}
	mi := &file_sgroups_domains_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SgIcmpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SgIcmpRule) ProtoMessage() {}

func (x *SgIcmpRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SgIcmpRule.ProtoReflect.Descriptor instead.
func (*SgIcmpRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{13}
}

func (x *SgIcmpRule) GetSG() string {
	if x != nil {
		return x.SG
	}
	return ""
}

func (x *SgIcmpRule) GetICMP() *common.ICMP {
	if x != nil {
		return x.ICMP
	}
	return nil
}

func (x *SgIcmpRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *SgIcmpRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *SgIcmpRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

// SG-SG:ICMP type rule
type SgSgIcmpRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security group name
	SgFrom string `protobuf:"bytes,1,opt,name=sgFrom,proto3" json:"sgFrom,omitempty"`
	// Security group name
	SgTo string `protobuf:"bytes,2,opt,name=sgTo,proto3" json:"sgTo,omitempty"`
	// ICMP spec
	ICMP *common.ICMP `protobuf:"bytes,3,opt,name=ICMP,proto3" json:"ICMP,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,4,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} trace in rules
	Trace bool `protobuf:"varint,5,opt,name=trace,proto3" json:"trace,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,6,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SgSgIcmpRule) Reset() {
	*x = SgSgIcmpRule{}
	mi := &file_sgroups_domains_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SgSgIcmpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SgSgIcmpRule) ProtoMessage() {}

func (x *SgSgIcmpRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SgSgIcmpRule.ProtoReflect.Descriptor instead.
func (*SgSgIcmpRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{14}
}

func (x *SgSgIcmpRule) GetSgFrom() string {
	if x != nil {
		return x.SgFrom
	}
	return ""
}

func (x *SgSgIcmpRule) GetSgTo() string {
	if x != nil {
		return x.SgTo
	}
	return ""
}

func (x *SgSgIcmpRule) GetICMP() *common.ICMP {
	if x != nil {
		return x.ICMP
	}
	return nil
}

func (x *SgSgIcmpRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *SgSgIcmpRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *SgSgIcmpRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *SgSgIcmpRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

// CIDR-SG NET-SG Ingress Egress type rule
type IECidrSgRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip net transport [TCP, UDP]
	Transport common.Networks_NetIP_Transport `protobuf:"varint,1,opt,name=transport,proto3,enum=common.Networks_NetIP_Transport" json:"transport,omitempty"`
	// CIDR subnetwork IPv4|IPv6
	CIDR string `protobuf:"bytes,2,opt,name=CIDR,proto3" json:"CIDR,omitempty"`
	// SG security group name
	SG string `protobuf:"bytes,3,opt,name=SG,proto3" json:"SG,omitempty"`
	// traffic direction [INGERSS, EGRESS]
	Traffic common.Traffic `protobuf:"varint,4,opt,name=traffic,proto3,enum=common.Traffic" json:"traffic,omitempty"`
	// AccPorts: access port set(s)
	Ports []*AccPorts `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,6,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} logs in rules
	Trace bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,8,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,9,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IECidrSgRule) Reset() {
	*x = IECidrSgRule{}
	mi := &file_sgroups_domains_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IECidrSgRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IECidrSgRule) ProtoMessage() {}

func (x *IECidrSgRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IECidrSgRule.ProtoReflect.Descriptor instead.
func (*IECidrSgRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{15}
}

func (x *IECidrSgRule) GetTransport() common.Networks_NetIP_Transport {
	if x != nil {
		return x.Transport
	}
	return common.Networks_NetIP_Transport(0)
}

func (x *IECidrSgRule) GetCIDR() string {
	if x != nil {
		return x.CIDR
	}
	return ""
}

func (x *IECidrSgRule) GetSG() string {
	if x != nil {
		return x.SG
	}
	return ""
}

func (x *IECidrSgRule) GetTraffic() common.Traffic {
	if x != nil {
		return x.Traffic
	}
	return common.Traffic(0)
}

func (x *IECidrSgRule) GetPorts() []*AccPorts {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *IECidrSgRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *IECidrSgRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *IECidrSgRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *IECidrSgRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

// CIDR-SG ICMP <in|e>gress type rule
type IECidrSgIcmpRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CIDR subnetwork IPv4|IPv6
	CIDR string `protobuf:"bytes,1,opt,name=CIDR,proto3" json:"CIDR,omitempty"`
	// SG security group name
	SG string `protobuf:"bytes,2,opt,name=SG,proto3" json:"SG,omitempty"`
	// traffic direction [INGERSS, EGRESS]
	Traffic common.Traffic `protobuf:"varint,3,opt,name=traffic,proto3,enum=common.Traffic" json:"traffic,omitempty"`
	// ICMP spec
	ICMP *common.ICMP `protobuf:"bytes,4,opt,name=ICMP,proto3" json:"ICMP,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,6,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} logs in rules
	Trace bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,8,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,9,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IECidrSgIcmpRule) Reset() {
	*x = IECidrSgIcmpRule{}
	mi := &file_sgroups_domains_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IECidrSgIcmpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IECidrSgIcmpRule) ProtoMessage() {}

func (x *IECidrSgIcmpRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IECidrSgIcmpRule.ProtoReflect.Descriptor instead.
func (*IECidrSgIcmpRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{16}
}

func (x *IECidrSgIcmpRule) GetCIDR() string {
	if x != nil {
		return x.CIDR
	}
	return ""
}

func (x *IECidrSgIcmpRule) GetSG() string {
	if x != nil {
		return x.SG
	}
	return ""
}

func (x *IECidrSgIcmpRule) GetTraffic() common.Traffic {
	if x != nil {
		return x.Traffic
	}
	return common.Traffic(0)
}

func (x *IECidrSgIcmpRule) GetICMP() *common.ICMP {
	if x != nil {
		return x.ICMP
	}
	return nil
}

func (x *IECidrSgIcmpRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *IECidrSgIcmpRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *IECidrSgIcmpRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *IECidrSgIcmpRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

// SG-SG <in|e>gress type rule
type IESgSgRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip net transport [TCP, UDP]
	Transport common.Networks_NetIP_Transport `protobuf:"varint,1,opt,name=transport,proto3,enum=common.Networks_NetIP_Transport" json:"transport,omitempty"`
	// Security group name which will be src/dst of traffic when ingress/egress option chosen
	SG string `protobuf:"bytes,2,opt,name=SG,proto3" json:"SG,omitempty"`
	// Security group name which will be src when egress chosen, and dst when ingress
	SgLocal string `protobuf:"bytes,3,opt,name=sg_local,json=sgLocal,proto3" json:"sg_local,omitempty"`
	// traffic direction [INGERSS, EGRESS]
	Traffic common.Traffic `protobuf:"varint,4,opt,name=traffic,proto3,enum=common.Traffic" json:"traffic,omitempty"`
	// AccPorts: access port set(s)
	Ports []*AccPorts `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,6,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} logs in rules
	Trace bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,8,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,9,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IESgSgRule) Reset() {
	*x = IESgSgRule{}
	mi := &file_sgroups_domains_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IESgSgRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IESgSgRule) ProtoMessage() {}

func (x *IESgSgRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IESgSgRule.ProtoReflect.Descriptor instead.
func (*IESgSgRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{17}
}

func (x *IESgSgRule) GetTransport() common.Networks_NetIP_Transport {
	if x != nil {
		return x.Transport
	}
	return common.Networks_NetIP_Transport(0)
}

func (x *IESgSgRule) GetSG() string {
	if x != nil {
		return x.SG
	}
	return ""
}

func (x *IESgSgRule) GetSgLocal() string {
	if x != nil {
		return x.SgLocal
	}
	return ""
}

func (x *IESgSgRule) GetTraffic() common.Traffic {
	if x != nil {
		return x.Traffic
	}
	return common.Traffic(0)
}

func (x *IESgSgRule) GetPorts() []*AccPorts {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *IESgSgRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *IESgSgRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *IESgSgRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *IESgSgRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

// SG-SG:ICMP <in|e>gress type rule
type IESgSgIcmpRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security group name
	SG string `protobuf:"bytes,1,opt,name=SG,proto3" json:"SG,omitempty"`
	// Security group name
	SgLocal string `protobuf:"bytes,2,opt,name=sg_local,json=sgLocal,proto3" json:"sg_local,omitempty"`
	// traffic direction [INGERSS, EGRESS]
	Traffic common.Traffic `protobuf:"varint,3,opt,name=traffic,proto3,enum=common.Traffic" json:"traffic,omitempty"`
	// ICMP spec
	ICMP *common.ICMP `protobuf:"bytes,4,opt,name=ICMP,proto3" json:"ICMP,omitempty"`
	// logs: switch-{ON|OFF} logs in rules
	Logs bool `protobuf:"varint,5,opt,name=logs,proto3" json:"logs,omitempty"`
	// trace: switch-{ON|OFF} trace in rules
	Trace bool `protobuf:"varint,6,opt,name=trace,proto3" json:"trace,omitempty"`
	// action: represents rule action
	Action RuleAction `protobuf:"varint,7,opt,name=action,proto3,enum=hbf.v2.sgroups.RuleAction" json:"action,omitempty"`
	// priority: rule priority affects on rule pos in its rule list
	Priority      *RulePriority `protobuf:"bytes,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IESgSgIcmpRule) Reset() {
	*x = IESgSgIcmpRule{}
	mi := &file_sgroups_domains_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IESgSgIcmpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IESgSgIcmpRule) ProtoMessage() {}

func (x *IESgSgIcmpRule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IESgSgIcmpRule.ProtoReflect.Descriptor instead.
func (*IESgSgIcmpRule) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{18}
}

func (x *IESgSgIcmpRule) GetSG() string {
	if x != nil {
		return x.SG
	}
	return ""
}

func (x *IESgSgIcmpRule) GetSgLocal() string {
	if x != nil {
		return x.SgLocal
	}
	return ""
}

func (x *IESgSgIcmpRule) GetTraffic() common.Traffic {
	if x != nil {
		return x.Traffic
	}
	return common.Traffic(0)
}

func (x *IESgSgIcmpRule) GetICMP() *common.ICMP {
	if x != nil {
		return x.ICMP
	}
	return nil
}

func (x *IESgSgIcmpRule) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *IESgSgIcmpRule) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *IESgSgIcmpRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_UNDEF
}

func (x *IESgSgIcmpRule) GetPriority() *RulePriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

type ProtoSpec_Ports struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*AccPorts            `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSpec_Ports) Reset() {
	*x = ProtoSpec_Ports{}
	mi := &file_sgroups_domains_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSpec_Ports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSpec_Ports) ProtoMessage() {}

func (x *ProtoSpec_Ports) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSpec_Ports.ProtoReflect.Descriptor instead.
func (*ProtoSpec_Ports) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ProtoSpec_Ports) GetPorts() []*AccPorts {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ProtoSpec_IcmpTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []int32                `protobuf:"varint,1,rep,packed,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSpec_IcmpTypes) Reset() {
	*x = ProtoSpec_IcmpTypes{}
	mi := &file_sgroups_domains_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSpec_IcmpTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSpec_IcmpTypes) ProtoMessage() {}

func (x *ProtoSpec_IcmpTypes) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_domains_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSpec_IcmpTypes.ProtoReflect.Descriptor instead.
func (*ProtoSpec_IcmpTypes) Descriptor() ([]byte, []int) {
	return file_sgroups_domains_proto_rawDescGZIP(), []int{7, 1}
}

func (x *ProtoSpec_IcmpTypes) GetTypes() []int32 {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_sgroups_domains_proto protoreflect.FileDescriptor

const file_sgroups_domains_proto_rawDesc = "" +
	"\n" +
	"\x15sgroups/domains.proto\x12\x0ehbf.v2.sgroups\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x19common/ip-transport.proto\"&\n" +
	"\bAccPorts\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s\x12\f\n" +
	"\x01d\x18\x02 \x01(\tR\x01d\"-\n" +
	"\fRulePriority\x12\x14\n" +
	"\x04some\x18\x01 \x01(\x05H\x00R\x04someB\a\n" +
	"\x05value\"]\n" +
	"\aNetwork\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\anetwork\x18\x02 \x01(\v2\x16.common.Networks.NetIPR\anetwork:\f\x92A\t\n" +
	"\a\xd2\x01\x04name\"\xa7\x02\n" +
	"\bSecGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bnetworks\x18\x02 \x03(\tR\bnetworks\x12M\n" +
	"\x0edefault_action\x18\x03 \x01(\x0e2&.hbf.v2.sgroups.SecGroup.DefaultActionR\rdefaultAction\x12\x14\n" +
	"\x05trace\x18\x04 \x01(\bR\x05trace\x12\x12\n" +
	"\x04logs\x18\x05 \x01(\bR\x04logs\x12\x14\n" +
	"\x05hosts\x18\x06 \x03(\tR\x05hosts\x12\x1a\n" +
	"\bservices\x18\a \x03(\tR\bservices\"2\n" +
	"\rDefaultAction\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\b\n" +
	"\x04DROP\x10\x01\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x02:\f\x92A\t\n" +
	"\a\xd2\x01\x04name\"\x1a\n" +
	"\x06IPList\x12\x10\n" +
	"\x03IPs\x18\x01 \x03(\tR\x03IPs\"x\n" +
	"\x04Host\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x17\n" +
	"\asg_name\x18\x03 \x01(\tR\x06sgName\x12/\n" +
	"\aip_list\x18\x04 \x01(\v2\x16.hbf.v2.sgroups.IPListR\x06ipList\"^\n" +
	"\tHostIPSet\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12/\n" +
	"\aip_list\x18\x02 \x01(\v2\x16.hbf.v2.sgroups.IPListR\x06ipList:\f\x92A\t\n" +
	"\a\xd2\x01\x04uuid\"\xc7\x02\n" +
	"\tProtoSpec\x121\n" +
	"\x03tcp\x18\x01 \x01(\v2\x1f.hbf.v2.sgroups.ProtoSpec.PortsR\x03tcp\x121\n" +
	"\x03udp\x18\x02 \x01(\v2\x1f.hbf.v2.sgroups.ProtoSpec.PortsR\x03udp\x12;\n" +
	"\x06icmpv4\x18\x03 \x01(\v2#.hbf.v2.sgroups.ProtoSpec.IcmpTypesR\x06icmpv4\x12;\n" +
	"\x06icmpv6\x18\x04 \x01(\v2#.hbf.v2.sgroups.ProtoSpec.IcmpTypesR\x06icmpv6\x1a7\n" +
	"\x05Ports\x12.\n" +
	"\x05ports\x18\x01 \x03(\v2\x18.hbf.v2.sgroups.AccPortsR\x05ports\x1a!\n" +
	"\tIcmpTypes\x12\x14\n" +
	"\x05types\x18\x01 \x03(\x05R\x05types\"\x7f\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tprotocols\x18\x02 \x01(\v2\x19.hbf.v2.sgroups.ProtoSpecR\tprotocols\x12\x19\n" +
	"\bsg_names\x18\x03 \x03(\tR\asgNames:\f\x92A\t\n" +
	"\a\xd2\x01\x04name\"\x8a\x02\n" +
	"\n" +
	"SvcSvcRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bsvc_from\x18\x02 \x01(\tR\asvcFrom\x12\x15\n" +
	"\x06svc_to\x18\x03 \x01(\tR\x05svcTo\x122\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\x05 \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority\x12\x12\n" +
	"\x04logs\x18\x06 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\a \x01(\bR\x05trace:\x1e\x92A\x1b\n" +
	"\x19\xd2\x01\x04name\xd2\x01\asvcFrom\xd2\x01\x05svcTo\"\xcd\x02\n" +
	"\bSgSgRule\x12\x17\n" +
	"\asg_from\x18\x01 \x01(\tR\x06sgFrom\x12\x13\n" +
	"\x05sg_to\x18\x02 \x01(\tR\x04sgTo\x12>\n" +
	"\ttransport\x18\x03 \x01(\x0e2 .common.Networks.NetIP.TransportR\ttransport\x12.\n" +
	"\x05ports\x18\x04 \x03(\v2\x18.hbf.v2.sgroups.AccPortsR\x05ports\x12\x12\n" +
	"\x04logs\x18\x05 \x01(\bR\x04logs\x122\n" +
	"\x06action\x18\x06 \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\a \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority:!\x92A\x1e\n" +
	"\x1c\xd2\x01\x06sgFrom\xd2\x01\x04sgTo\xd2\x01\ttransport\"\xcc\x02\n" +
	"\bFqdnRule\x12\x17\n" +
	"\asg_from\x18\x01 \x01(\tR\x06sgFrom\x12\x12\n" +
	"\x04FQDN\x18\x02 \x01(\tR\x04FQDN\x12>\n" +
	"\ttransport\x18\x03 \x01(\x0e2 .common.Networks.NetIP.TransportR\ttransport\x12.\n" +
	"\x05ports\x18\x04 \x03(\v2\x18.hbf.v2.sgroups.AccPortsR\x05ports\x12\x12\n" +
	"\x04logs\x18\x05 \x01(\bR\x04logs\x122\n" +
	"\x06action\x18\a \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\b \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority:!\x92A\x1e\n" +
	"\x1c\xd2\x01\x06sgFrom\xd2\x01\x04FQDN\xd2\x01\ttransport\"\x84\x03\n" +
	"\vSvcFqdnRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bsvc_from\x18\x02 \x01(\tR\asvcFrom\x12\x12\n" +
	"\x04FQDN\x18\x03 \x01(\tR\x04FQDN\x12>\n" +
	"\ttransport\x18\x04 \x01(\x0e2 .common.Networks.NetIP.TransportR\ttransport\x12.\n" +
	"\x05ports\x18\x05 \x03(\v2\x18.hbf.v2.sgroups.AccPortsR\x05ports\x12\x12\n" +
	"\x04logs\x18\x06 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\a \x01(\bR\x05trace\x122\n" +
	"\x06action\x18\b \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\t \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority:*\x92A'\n" +
	"%\xd2\x01\x04name\xd2\x01\bsvc_from\xd2\x01\x04FQDN\xd2\x01\ttransport\"\x9c\x01\n" +
	"\n" +
	"SgIcmpRule\x12\x0e\n" +
	"\x02SG\x18\x01 \x01(\tR\x02SG\x12 \n" +
	"\x04ICMP\x18\x02 \x01(\v2\f.common.ICMPR\x04ICMP\x12\x12\n" +
	"\x04logs\x18\x03 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\x04 \x01(\bR\x05trace\x122\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\"\xf4\x01\n" +
	"\fSgSgIcmpRule\x12\x16\n" +
	"\x06sgFrom\x18\x01 \x01(\tR\x06sgFrom\x12\x12\n" +
	"\x04sgTo\x18\x02 \x01(\tR\x04sgTo\x12 \n" +
	"\x04ICMP\x18\x03 \x01(\v2\f.common.ICMPR\x04ICMP\x12\x12\n" +
	"\x04logs\x18\x04 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\x05 \x01(\bR\x05trace\x122\n" +
	"\x06action\x18\x06 \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\a \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority\"\x8e\x03\n" +
	"\fIECidrSgRule\x12>\n" +
	"\ttransport\x18\x01 \x01(\x0e2 .common.Networks.NetIP.TransportR\ttransport\x12\x12\n" +
	"\x04CIDR\x18\x02 \x01(\tR\x04CIDR\x12\x0e\n" +
	"\x02SG\x18\x03 \x01(\tR\x02SG\x12)\n" +
	"\atraffic\x18\x04 \x01(\x0e2\x0f.common.TrafficR\atraffic\x12.\n" +
	"\x05ports\x18\x05 \x03(\v2\x18.hbf.v2.sgroups.AccPortsR\x05ports\x12\x12\n" +
	"\x04logs\x18\x06 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\a \x01(\bR\x05trace\x122\n" +
	"\x06action\x18\b \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\t \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority:'\x92A$\n" +
	"\"\xd2\x01\x04CIDR\xd2\x01\x02SG\xd2\x01\ttransport\xd2\x01\atraffic\"\xc3\x02\n" +
	"\x10IECidrSgIcmpRule\x12\x12\n" +
	"\x04CIDR\x18\x01 \x01(\tR\x04CIDR\x12\x0e\n" +
	"\x02SG\x18\x02 \x01(\tR\x02SG\x12)\n" +
	"\atraffic\x18\x03 \x01(\x0e2\x0f.common.TrafficR\atraffic\x12 \n" +
	"\x04ICMP\x18\x04 \x01(\v2\f.common.ICMPR\x04ICMP\x12\x12\n" +
	"\x04logs\x18\x06 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\a \x01(\bR\x05trace\x122\n" +
	"\x06action\x18\b \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\t \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority:&\x92A#\n" +
	"!\xd2\x01\x04CIDR\xd2\x01\x02SG\xd2\x01\atraffic\xd2\x01\bICMP.IPv\"\x96\x03\n" +
	"\n" +
	"IESgSgRule\x12>\n" +
	"\ttransport\x18\x01 \x01(\x0e2 .common.Networks.NetIP.TransportR\ttransport\x12\x0e\n" +
	"\x02SG\x18\x02 \x01(\tR\x02SG\x12\x19\n" +
	"\bsg_local\x18\x03 \x01(\tR\asgLocal\x12)\n" +
	"\atraffic\x18\x04 \x01(\x0e2\x0f.common.TrafficR\atraffic\x12.\n" +
	"\x05ports\x18\x05 \x03(\v2\x18.hbf.v2.sgroups.AccPortsR\x05ports\x12\x12\n" +
	"\x04logs\x18\x06 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\a \x01(\bR\x05trace\x122\n" +
	"\x06action\x18\b \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\t \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority:*\x92A'\n" +
	"%\xd2\x01\x02SG\xd2\x01\asgLocal\xd2\x01\ttransport\xd2\x01\atraffic\"\xcb\x02\n" +
	"\x0eIESgSgIcmpRule\x12\x0e\n" +
	"\x02SG\x18\x01 \x01(\tR\x02SG\x12\x19\n" +
	"\bsg_local\x18\x02 \x01(\tR\asgLocal\x12)\n" +
	"\atraffic\x18\x03 \x01(\x0e2\x0f.common.TrafficR\atraffic\x12 \n" +
	"\x04ICMP\x18\x04 \x01(\v2\f.common.ICMPR\x04ICMP\x12\x12\n" +
	"\x04logs\x18\x05 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\x06 \x01(\bR\x05trace\x122\n" +
	"\x06action\x18\a \x01(\x0e2\x1a.hbf.v2.sgroups.RuleActionR\x06action\x128\n" +
	"\bpriority\x18\b \x01(\v2\x1c.hbf.v2.sgroups.RulePriorityR\bpriority:)\x92A&\n" +
	"$\xd2\x01\x02SG\xd2\x01\asgLocal\xd2\x01\atraffic\xd2\x01\bICMP.IPv*-\n" +
	"\n" +
	"RuleAction\x12\t\n" +
	"\x05UNDEF\x10\x00\x12\b\n" +
	"\x04DROP\x10\x01\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x02B8Z6github.com/PRO-Robotech/protos/pkg/api/sgroups;sgroupsb\x06proto3"

var (
	file_sgroups_domains_proto_rawDescOnce sync.Once
	file_sgroups_domains_proto_rawDescData []byte
)

func file_sgroups_domains_proto_rawDescGZIP() []byte {
	file_sgroups_domains_proto_rawDescOnce.Do(func() {
		file_sgroups_domains_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sgroups_domains_proto_rawDesc), len(file_sgroups_domains_proto_rawDesc)))
	})
	return file_sgroups_domains_proto_rawDescData
}

var file_sgroups_domains_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sgroups_domains_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sgroups_domains_proto_goTypes = []any{
	(RuleAction)(0),                      // 0: hbf.v2.sgroups.RuleAction
	(SecGroup_DefaultAction)(0),          // 1: hbf.v2.sgroups.SecGroup.DefaultAction
	(*AccPorts)(nil),                     // 2: hbf.v2.sgroups.AccPorts
	(*RulePriority)(nil),                 // 3: hbf.v2.sgroups.RulePriority
	(*Network)(nil),                      // 4: hbf.v2.sgroups.Network
	(*SecGroup)(nil),                     // 5: hbf.v2.sgroups.SecGroup
	(*IPList)(nil),                       // 6: hbf.v2.sgroups.IPList
	(*Host)(nil),                         // 7: hbf.v2.sgroups.Host
	(*HostIPSet)(nil),                    // 8: hbf.v2.sgroups.HostIPSet
	(*ProtoSpec)(nil),                    // 9: hbf.v2.sgroups.ProtoSpec
	(*Service)(nil),                      // 10: hbf.v2.sgroups.Service
	(*SvcSvcRule)(nil),                   // 11: hbf.v2.sgroups.SvcSvcRule
	(*SgSgRule)(nil),                     // 12: hbf.v2.sgroups.SgSgRule
	(*FqdnRule)(nil),                     // 13: hbf.v2.sgroups.FqdnRule
	(*SvcFqdnRule)(nil),                  // 14: hbf.v2.sgroups.SvcFqdnRule
	(*SgIcmpRule)(nil),                   // 15: hbf.v2.sgroups.SgIcmpRule
	(*SgSgIcmpRule)(nil),                 // 16: hbf.v2.sgroups.SgSgIcmpRule
	(*IECidrSgRule)(nil),                 // 17: hbf.v2.sgroups.IECidrSgRule
	(*IECidrSgIcmpRule)(nil),             // 18: hbf.v2.sgroups.IECidrSgIcmpRule
	(*IESgSgRule)(nil),                   // 19: hbf.v2.sgroups.IESgSgRule
	(*IESgSgIcmpRule)(nil),               // 20: hbf.v2.sgroups.IESgSgIcmpRule
	(*ProtoSpec_Ports)(nil),              // 21: hbf.v2.sgroups.ProtoSpec.Ports
	(*ProtoSpec_IcmpTypes)(nil),          // 22: hbf.v2.sgroups.ProtoSpec.IcmpTypes
	(*common.Networks_NetIP)(nil),        // 23: common.Networks.NetIP
	(common.Networks_NetIP_Transport)(0), // 24: common.Networks.NetIP.Transport
	(*common.ICMP)(nil),                  // 25: common.ICMP
	(common.Traffic)(0),                  // 26: common.Traffic
}
var file_sgroups_domains_proto_depIdxs = []int32{
	23, // 0: hbf.v2.sgroups.Network.network:type_name -> common.Networks.NetIP
	1,  // 1: hbf.v2.sgroups.SecGroup.default_action:type_name -> hbf.v2.sgroups.SecGroup.DefaultAction
	6,  // 2: hbf.v2.sgroups.Host.ip_list:type_name -> hbf.v2.sgroups.IPList
	6,  // 3: hbf.v2.sgroups.HostIPSet.ip_list:type_name -> hbf.v2.sgroups.IPList
	21, // 4: hbf.v2.sgroups.ProtoSpec.tcp:type_name -> hbf.v2.sgroups.ProtoSpec.Ports
	21, // 5: hbf.v2.sgroups.ProtoSpec.udp:type_name -> hbf.v2.sgroups.ProtoSpec.Ports
	22, // 6: hbf.v2.sgroups.ProtoSpec.icmpv4:type_name -> hbf.v2.sgroups.ProtoSpec.IcmpTypes
	22, // 7: hbf.v2.sgroups.ProtoSpec.icmpv6:type_name -> hbf.v2.sgroups.ProtoSpec.IcmpTypes
	9,  // 8: hbf.v2.sgroups.Service.protocols:type_name -> hbf.v2.sgroups.ProtoSpec
	0,  // 9: hbf.v2.sgroups.SvcSvcRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 10: hbf.v2.sgroups.SvcSvcRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	24, // 11: hbf.v2.sgroups.SgSgRule.transport:type_name -> common.Networks.NetIP.Transport
	2,  // 12: hbf.v2.sgroups.SgSgRule.ports:type_name -> hbf.v2.sgroups.AccPorts
	0,  // 13: hbf.v2.sgroups.SgSgRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 14: hbf.v2.sgroups.SgSgRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	24, // 15: hbf.v2.sgroups.FqdnRule.transport:type_name -> common.Networks.NetIP.Transport
	2,  // 16: hbf.v2.sgroups.FqdnRule.ports:type_name -> hbf.v2.sgroups.AccPorts
	0,  // 17: hbf.v2.sgroups.FqdnRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 18: hbf.v2.sgroups.FqdnRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	24, // 19: hbf.v2.sgroups.SvcFqdnRule.transport:type_name -> common.Networks.NetIP.Transport
	2,  // 20: hbf.v2.sgroups.SvcFqdnRule.ports:type_name -> hbf.v2.sgroups.AccPorts
	0,  // 21: hbf.v2.sgroups.SvcFqdnRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 22: hbf.v2.sgroups.SvcFqdnRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	25, // 23: hbf.v2.sgroups.SgIcmpRule.ICMP:type_name -> common.ICMP
	0,  // 24: hbf.v2.sgroups.SgIcmpRule.action:type_name -> hbf.v2.sgroups.RuleAction
	25, // 25: hbf.v2.sgroups.SgSgIcmpRule.ICMP:type_name -> common.ICMP
	0,  // 26: hbf.v2.sgroups.SgSgIcmpRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 27: hbf.v2.sgroups.SgSgIcmpRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	24, // 28: hbf.v2.sgroups.IECidrSgRule.transport:type_name -> common.Networks.NetIP.Transport
	26, // 29: hbf.v2.sgroups.IECidrSgRule.traffic:type_name -> common.Traffic
	2,  // 30: hbf.v2.sgroups.IECidrSgRule.ports:type_name -> hbf.v2.sgroups.AccPorts
	0,  // 31: hbf.v2.sgroups.IECidrSgRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 32: hbf.v2.sgroups.IECidrSgRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	26, // 33: hbf.v2.sgroups.IECidrSgIcmpRule.traffic:type_name -> common.Traffic
	25, // 34: hbf.v2.sgroups.IECidrSgIcmpRule.ICMP:type_name -> common.ICMP
	0,  // 35: hbf.v2.sgroups.IECidrSgIcmpRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 36: hbf.v2.sgroups.IECidrSgIcmpRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	24, // 37: hbf.v2.sgroups.IESgSgRule.transport:type_name -> common.Networks.NetIP.Transport
	26, // 38: hbf.v2.sgroups.IESgSgRule.traffic:type_name -> common.Traffic
	2,  // 39: hbf.v2.sgroups.IESgSgRule.ports:type_name -> hbf.v2.sgroups.AccPorts
	0,  // 40: hbf.v2.sgroups.IESgSgRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 41: hbf.v2.sgroups.IESgSgRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	26, // 42: hbf.v2.sgroups.IESgSgIcmpRule.traffic:type_name -> common.Traffic
	25, // 43: hbf.v2.sgroups.IESgSgIcmpRule.ICMP:type_name -> common.ICMP
	0,  // 44: hbf.v2.sgroups.IESgSgIcmpRule.action:type_name -> hbf.v2.sgroups.RuleAction
	3,  // 45: hbf.v2.sgroups.IESgSgIcmpRule.priority:type_name -> hbf.v2.sgroups.RulePriority
	2,  // 46: hbf.v2.sgroups.ProtoSpec.Ports.ports:type_name -> hbf.v2.sgroups.AccPorts
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_sgroups_domains_proto_init() }
func file_sgroups_domains_proto_init() {
	if File_sgroups_domains_proto != nil {
		return
	}
	file_sgroups_domains_proto_msgTypes[1].OneofWrappers = []any{
		(*RulePriority_Some)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgroups_domains_proto_rawDesc), len(file_sgroups_domains_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgroups_domains_proto_goTypes,
		DependencyIndexes: file_sgroups_domains_proto_depIdxs,
		EnumInfos:         file_sgroups_domains_proto_enumTypes,
		MessageInfos:      file_sgroups_domains_proto_msgTypes,
	}.Build()
	File_sgroups_domains_proto = out.File
	file_sgroups_domains_proto_goTypes = nil
	file_sgroups_domains_proto_depIdxs = nil
}
