syntax = "proto3";

package hbf.v2.sgroups;
option go_package = "github.com/PRO-Robotech/protos/pkg/api/sgroups;sgroups";

import "protoc-gen-openapiv2/options/annotations.proto";

import "common/ip-transport.proto";

// AccPorts: represents Security Group Rule access source-dest ports
message AccPorts {
  //source port "num" or port range "num1-num2"
  string s = 1;
  //destination  port "num" or port range "num1-num2"
  string d = 2;
}

// RuleAction: represents verdict action for rules
enum RuleAction {
  //Undefined verdict action
  UNDEF = 0;

  //Drops net packet
  DROP = 1;

  //Accepts net packet
  ACCEPT = 2;
}

// RulePriority: represents rule priority or none if we no need use it
message RulePriority {
  oneof value {
    int32 some = 1;
  }
}

// Network: represents a named IP network
message Network {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["name"]
    }
  };
  //the name of network
  string name = 1;
  //network in CIDR form
  common.Networks.NetIP network = 2;
}

// SecGroup: represents a security group
message SecGroup {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["name"]
    }
  };
  // DefaultAction: represents default action at end of chains for Security Gpoup
  enum DefaultAction {
    //Default is default action in [DROP|ACCEPT]
    DEFAULT = 0;

    //Drops net packet
    DROP = 1;

    //Accepts net packet
    ACCEPT = 2;
  }
  //name of security group
  string name = 1;
  //related to security gpoup network(s)
  repeated string networks = 2;
  //default_action: represents default rule action
  DefaultAction default_action = 3;
  //trace: set or unset 'nftrace' flag
  bool trace = 4;
  //logs: switch-{ON|OFF} logs in chain
  bool logs = 5;
  //host: related to security group host names
  repeated string hosts = 6;
  //services: related to security group service names
  repeated string services = 7;
}

// IPList : list of hosts IPs
message IPList {
   repeated string IPs = 1;
}

// Host: represents a host with its name, UUID, and IPs related to Security Group(s)
message Host {
   string name = 1;
   string uuid = 2;
   string sg_name = 3;
   IPList ip_list = 4;
}

// ProtoSpec: represents protocols specification (ports, icmp types)
message ProtoSpec {
  message Ports {
    repeated AccPorts ports = 1;
  }
  message IcmpTypes {
    repeated int32 types = 1;
  }
  // tcp ports
  Ports tcp = 1;
  // udp ports
  Ports udp = 2;
  // icmpv4 types
  IcmpTypes icmpv4 = 3;
  // icmpv6 types
  IcmpTypes icmpv6 = 4;
}

// Service: represents a service resource
message Service {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["name"]
    }
  };

  // name of service
  string name = 1;
  // protocols specification (ports, icmp types)
  ProtoSpec protocols = 2;
  // related to security group name(s)
  repeated string sg_names = 3;
}

// SvcSvcRule: represents Service-to-Service Rule
message SvcSvcRule {
   option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
      json_schema: {
        required: ["name", "svcFrom", "svcTo"]
      }
   };
   // name of service
   string name = 1;
   //service at client
   string svc_from = 2;
   //service at server
   string svc_to = 3;
   //action: represents rule action
   RuleAction action = 4;
   //priority: rule priority affects on rule pos in its rule list
   RulePriority priority = 5;
   // logs: switch-{ON|OFF} logs in rules
   bool logs = 6;
   // trace: switch-{ON|OFF} trace in rules
   bool trace = 7;
}

// SgSgRule: represents Security Groups Rule
message SgSgRule {
   option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
      json_schema: {
        required: ["sgFrom", "sgTo", "transport"]
      }
   };
   //security group at client
   string sg_from = 1;
   //security group at server
   string sg_to = 2;
   //ip net transport
   common.Networks.NetIP.Transport transport = 3;
   //access ports set
   repeated AccPorts ports = 4;
   //logs: switch-{ON|OFF} logs in rules
   bool logs = 5;
   //action: represents rule action
   RuleAction action = 6;
   //priority: rule priority affects on rule pos in its rule list
   RulePriority priority = 7;
}

// FqdnRule: represents Security Groups Rule
message FqdnRule {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
     json_schema: {
       required: ["sgFrom", "FQDN", "transport"]
     }
  };
  // security group at client
  string sg_from = 1;
  // FQDN full qualified domain name portable for DNS queries
  string FQDN = 2;
  // ip net transport
  common.Networks.NetIP.Transport transport = 3;
  // access ports set
  repeated AccPorts ports = 4;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 5;
  // protocols: L7 protocol list
  // repeated string protocols = 6;
  // action: represents rule action
  RuleAction action = 7;
  // priority: rule priority affects on rule pos in its rule list
  RulePriority priority = 8;
}

// SvcFqdnRule: represents Service to FQDN Rule
message SvcFqdnRule {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
     json_schema: {
       required: ["svc_from", "FQDN", "transport"]
     }
  };
  // service at client
  string svc_from = 1;
  // FQDN full qualified domain name portable for DNS queries
  string FQDN = 2;
  // ip net transport
  common.Networks.NetIP.Transport transport = 3;
  // access ports set
  repeated AccPorts ports = 4;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 5;
  // trace: switch-{ON|OFF} trace in rules
  bool trace = 6;
  // action: represents rule action
  RuleAction action = 7;
  // priority: rule priority affects on rule pos in its rule list
  RulePriority priority = 8;
}

// SG:ICMP type rule
message SgIcmpRule {
  // Security group name
  string SG = 1;
  // ICMP spec
  common.ICMP ICMP = 2;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 3;
  // trace: switch-{ON|OFF} trace in rules
  bool trace = 4;
  // action: represents rule action
  RuleAction action = 5;
}

// SG-SG:ICMP type rule
message SgSgIcmpRule {
  // Security group name
  string sgFrom = 1;
  // Security group name
  string sgTo = 2;
  // ICMP spec
  common.ICMP ICMP = 3;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 4;
  // trace: switch-{ON|OFF} trace in rules
  bool trace = 5;
  // action: represents rule action
  RuleAction action = 6;
  // priority: rule priority affects on rule pos in its rule list
  RulePriority priority = 7;
}

// CIDR-SG NET-SG Ingress Egress type rule
message IECidrSgRule {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: { 
      required: ["CIDR", "SG", "transport", "traffic"]
    }
  };
  // ip net transport [TCP, UDP]
  common.Networks.NetIP.Transport transport = 1;
  // CIDR subnetwork IPv4|IPv6
  string CIDR = 2;
  // SG security group name
  string SG = 3;
  // traffic direction [INGERSS, EGRESS]
  common.Traffic traffic = 4;
  // AccPorts: access port set(s)
  repeated AccPorts ports = 5;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 6;
  // trace: switch-{ON|OFF} logs in rules
  bool trace = 7;
  // action: represents rule action
  RuleAction action = 8;
  // priority: rule priority affects on rule pos in its rule list
  RulePriority priority = 9;
}

// CIDR-SG ICMP <in|e>gress type rule
message IECidrSgIcmpRule {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["CIDR", "SG", "traffic", "ICMP.IPv"]
    }
  };
  // CIDR subnetwork IPv4|IPv6
  string CIDR = 1;
  // SG security group name
  string SG = 2;
  // traffic direction [INGERSS, EGRESS]
  common.Traffic traffic = 3;
  // ICMP spec
  common.ICMP ICMP = 4;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 6;
  // trace: switch-{ON|OFF} logs in rules
  bool trace = 7;
  // action: represents rule action
  RuleAction action = 8;
  // priority: rule priority affects on rule pos in its rule list
  RulePriority priority = 9;
}

// SG-SG <in|e>gress type rule
message IESgSgRule {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["SG", "sgLocal", "transport", "traffic"]
    }
  };
  // ip net transport [TCP, UDP]
  common.Networks.NetIP.Transport transport = 1;
  // Security group name which will be src/dst of traffic when ingress/egress option chosen
  string SG = 2;
  // Security group name which will be src when egress chosen, and dst when ingress
  string sg_local = 3;
  // traffic direction [INGERSS, EGRESS]
  common.Traffic traffic = 4;
  // AccPorts: access port set(s)
  repeated AccPorts ports = 5;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 6;
  // trace: switch-{ON|OFF} logs in rules
  bool trace = 7;
  // action: represents rule action
  RuleAction action = 8;
  // priority: rule priority affects on rule pos in its rule list
  RulePriority priority = 9;
}

// SG-SG:ICMP <in|e>gress type rule
message IESgSgIcmpRule {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["SG", "sgLocal", "traffic", "ICMP.IPv"]
    }
  };
  // Security group name
  string SG = 1;
  // Security group name
  string sg_local = 2;
  // traffic direction [INGERSS, EGRESS]
  common.Traffic traffic = 3;
  // ICMP spec
  common.ICMP ICMP = 4;
  // logs: switch-{ON|OFF} logs in rules
  bool logs = 5;
  // trace: switch-{ON|OFF} trace in rules
  bool trace = 6;
  // action: represents rule action
  RuleAction action = 7;
  // priority: rule priority affects on rule pos in its rule list
  RulePriority priority = 8;
}