syntax = "proto3";

package hbf.v1.sgroups;
option go_package = "github.com/PRO-Robotech/protos/pkg/api/sgroups;sgroups";

import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

import "sgroups/queries.proto";
import "sgroups/domains.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Host Based Firewall";
    version: "1.0";
  };
  external_docs: {
    url: "https://h-bf.prorobotech.ru";
    description: "Documentation";
  }
  schemes: [HTTP];
  consumes: "application/json";
  produces: "application/json";
};


service SecGroupService {
   option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_tag) = { 
       description: "Security Groups API service"
   };

   rpc Sync(SyncReq) returns (google.protobuf.Empty) {
     option (google.api.http) = {
        post: "/v1/sync"
        body: "*"
        additional_bindings {
         post: "/v2/sync"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "Sync: makes changes in DB";
     };
   }

   rpc SyncStatus(google.protobuf.Empty) returns(SyncStatusResp){
     option (google.api.http) = {
        get: "/v1/sync/status"
        additional_bindings {
         get: "/v2/sync/status"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "SyncStatus: gets last succeeded update DB status";
     };
   }

   rpc SyncStatuses(google.protobuf.Empty) returns(stream SyncStatusResp){}

   rpc ListNetworks(ListNetworksReq) returns (ListNetworksResp) {
     option (google.api.http) = {
        post: "/v1/list-networks"
        body: "*"
        additional_bindings {
         post: "/v2/list-networks"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "ListNetworks: shows list of Network";
     };
   }

   rpc ListSecurityGroups(ListSecurityGroupsReq) returns (ListSecurityGroupsResp) {
     option (google.api.http) = {
        post: "/v1/list-security-groups"
        body: "*"
        additional_bindings {
         post: "/v2/list-security-groups"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "ListSecurityGroups: shows list of Security Groups";
     };
   }

   rpc ListHosts(ListHostsReq) returns (ListHostsResp) {
     option (google.api.http) = {
         post: "/v1/list-hosts"
         body: "*"
         additional_bindings {
          post: "/v2/list-hosts"
          body: "*"
         }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
         description: "ListHosts: list hosts by variety of scopes";
     };
   };

   rpc ListServices(ListServicesReq) returns (ListServicesResp) {
     option (google.api.http) = {
        post: "/v1/list-services"
        body: "*"
        additional_bindings {
         post: "/v2/list-services"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "ListServices: list services by variety of scopes";
     };
   }

   rpc ListSvcSvcRules(ListSvcSvcRulesReq) returns (ListSvcSvcRulesResp) {
     option (google.api.http) = {
        post: "/v1/list-service-rules"
        body: "*"
        additional_bindings {
         post: "/v2/list-service-rules"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "ListSvcSvcRules: lists Service-to-Service Rule(s) by variety of scopes'";
     };
   };

   rpc ListSvcFqdnRules(ListSvcFqdnRulesReq) returns (ListSvcFqdnRulesResp) {
     option (google.api.http) = {
        post: "/v1/list-service-fqdn-rules"
        body: "*"
        additional_bindings {
         post: "/v2/list-service-fqdn-rules"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "ListSvcFqdnRules: lists Service(s) FQDN Rule(s) by variety of scopes'";
     };
   };

   rpc ListIECidrSvcRules(ListIECidrSvcRulesReq) returns (ListIECidrSvcRulesResp) {
     option (google.api.http) = {
        post: "/v1/list-ie-cidr-svc-rules"
        body: "*"
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "ListIECidrSvcRules: lists CIDR-SVC-[INGRESS|EGRESS] Rule(s) by variety of scopes'";
     };
   };

   rpc GetSgSubnets(GetSgSubnetsReq) returns (GetSgSubnetsResp){
     option (google.api.http) = {
        get: "/v1/sg/{sg_name}/subnets"
        additional_bindings {
         get: "/v2/sg/{sg_name}/subnets"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "GetSgSubnets: gets Networks related to SG";
     };
   };

   rpc GetSecGroupForAddress(GetSecGroupForAddressReq) returns (SecGroup) {
     option (google.api.http) = {
        get: "/v1/{address}/sg"
        additional_bindings {
         get: "/v2/{address}/sg"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "GetSecGroupForAddress: gets Security Group by IP or CIDR";
     };
   };

   rpc GetSecGroupForHost(GetSecGroupForHostReq) returns (SecGroup) {
     option (google.api.http) = {
        get: "/v1/{host_name}/{host_uuid}/sg"
        additional_bindings {
         get: "/v2/{host_name}/{host_uuid}/sg"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "GetSecGroupForHost: gets Security Group by host info";
     };
   };

   rpc FindSgSgRules(FindSgSgRulesReq) returns (SgSgRulesResp) {
     option (google.api.http) = {
        post: "/v1/sg-sg-rules"
        body: "*"
        additional_bindings {
         post: "/v2/sg-sg-rules"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "FindSgSgRules: finds SG-SG Rule(s) scoped by variety pairs 'SG '->'to SG'";
     };
   };

   rpc FindFqdnRules(FindFqdnRulesReq) returns (FqdnRulesResp) {
     option (google.api.http) = {
        post: "/v1/fqdn-rules"
        body: "*"
        additional_bindings {
         post: "/v2/fqdn-rules"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "FindFqdnRules: finds FQDN Rule(s) scoped by variety SG 'from'";
     };
   };

   rpc FindSgIcmpRules(FindSgIcmpRulesReq) returns (SgIcmpRulesResp) {
     option (google.api.http) = {
        post: "/v1/sg-icmp-rules"
        body: "*"
        additional_bindings {
         post: "/v2/sg-icmp-rules"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "FindSgIcmpRules: finds SG:ICMP Rule(s) scoped by variety SG";
     };
   };

   rpc FindSgSgIcmpRules(FindSgSgIcmpRulesReq) returns (SgSgIcmpRulesResp) {
     option (google.api.http) = {
        post: "/v1/sg-sg-icmp-rules"
        body: "*"
        additional_bindings {
         post: "/v2/sg-sg-icmp-rules"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "FindSgSgIcmpRules: finds SG-SG:ICMP Rule(s) scoped by variety SG<FROM-TO>";
     };
   };

   rpc FindIECidrSgRules(FindIECidrSgRulesReq) returns (IECidrSgRulesResp) {
     option (google.api.http) = {
        post: "/v1/ie-cidr-sg-rules"
        body: "*"
        additional_bindings {
         post: "/v2/ie-cidr-sg-rules"
         body: "*"
        }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        description: "FindIECidrSgRules: finds CIDR-SG-[INGRESS+EGRESS] rule(s) scoped by variety SG";
     };
   };

   rpc FindIESgSgRules(FindIESgSgRulesReq) returns (IESgSgRulesResp) {
    option (google.api.http) = {
        post: "/v1/ie-sg-sg-rules"
        body: "*"
        additional_bindings {
         post: "/v2/ie-sg-sg-rules"
         body: "*"
        }
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "FindIESgSgRules: finds SG-SG-[INGRESS+EGRESS] rule(s) scoped by variety SG-<FROM|TO>"
    };
   };

   rpc FindIESgSgIcmpRules(FindIESgSgIcmpRulesReq) returns (IESgSgIcmpRulesResp) {
     option (google.api.http) = {
       post: "/v1/ie-sg-sg-icmp-rules"
       body: "*"
       additional_bindings {
        post: "/v2/ie-sg-sg-icmp-rules"
        body: "*"
       }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
       description: "FindSgSgIcmpRules: finds SG-SG-[INGRESS+EGRESS]:ICMP rule(s) scoped by variety SG-<FROM|TO>"
     };
   };

   rpc FindIECidrSgIcmpRules(FindIECidrSgIcmpRulesReq) returns (IECidrSgIcmpRulesResp) {
     option (google.api.http) = {
       post: "/v1/ie-cidr-sg-icmp-rules"
       body: "*"
       additional_bindings {
        post: "/v2/ie-cidr-sg-icmp-rules"
        body: "*"
       }
     };
     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
       description: "FindIECidrSgIcmpRules: finds CIDR-SG-[INGRESS|EGRESS]:ICMP rule(s) scoped by variety SG"
     };
   }

   rpc UpdHostIPSet(UpdHostIPSetReq) returns (google.protobuf.Empty) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "UpdHostIPSet: updates Host IPSet by host uuid"
    };
    option (google.api.http) = {
      post: "/v1/upd-host-ipset"
      body: "*"
      additional_bindings {
       post: "/v2/upd-host-ipset"
       body: "*"
      }
    };
   };
}