// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sgroups/v1/service.proto

package sgroupsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/PRO-Robotech/protos/pkg/api/sgroups/v1"
	empty "github.com/golang/protobuf/ptypes/empty"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SecGroupServiceName is the fully-qualified name of the SecGroupService service.
	SecGroupServiceName = "hbf.v1.sgroups.SecGroupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecGroupServiceSyncProcedure is the fully-qualified name of the SecGroupService's Sync RPC.
	SecGroupServiceSyncProcedure = "/hbf.v1.sgroups.SecGroupService/Sync"
	// SecGroupServiceSyncStatusProcedure is the fully-qualified name of the SecGroupService's
	// SyncStatus RPC.
	SecGroupServiceSyncStatusProcedure = "/hbf.v1.sgroups.SecGroupService/SyncStatus"
	// SecGroupServiceSyncStatusesProcedure is the fully-qualified name of the SecGroupService's
	// SyncStatuses RPC.
	SecGroupServiceSyncStatusesProcedure = "/hbf.v1.sgroups.SecGroupService/SyncStatuses"
	// SecGroupServiceListNetworksProcedure is the fully-qualified name of the SecGroupService's
	// ListNetworks RPC.
	SecGroupServiceListNetworksProcedure = "/hbf.v1.sgroups.SecGroupService/ListNetworks"
	// SecGroupServiceListSecurityGroupsProcedure is the fully-qualified name of the SecGroupService's
	// ListSecurityGroups RPC.
	SecGroupServiceListSecurityGroupsProcedure = "/hbf.v1.sgroups.SecGroupService/ListSecurityGroups"
	// SecGroupServiceListHostsProcedure is the fully-qualified name of the SecGroupService's ListHosts
	// RPC.
	SecGroupServiceListHostsProcedure = "/hbf.v1.sgroups.SecGroupService/ListHosts"
	// SecGroupServiceListServicesProcedure is the fully-qualified name of the SecGroupService's
	// ListServices RPC.
	SecGroupServiceListServicesProcedure = "/hbf.v1.sgroups.SecGroupService/ListServices"
	// SecGroupServiceListSvcSvcRulesProcedure is the fully-qualified name of the SecGroupService's
	// ListSvcSvcRules RPC.
	SecGroupServiceListSvcSvcRulesProcedure = "/hbf.v1.sgroups.SecGroupService/ListSvcSvcRules"
	// SecGroupServiceListSvcFqdnRulesProcedure is the fully-qualified name of the SecGroupService's
	// ListSvcFqdnRules RPC.
	SecGroupServiceListSvcFqdnRulesProcedure = "/hbf.v1.sgroups.SecGroupService/ListSvcFqdnRules"
	// SecGroupServiceGetSgSubnetsProcedure is the fully-qualified name of the SecGroupService's
	// GetSgSubnets RPC.
	SecGroupServiceGetSgSubnetsProcedure = "/hbf.v1.sgroups.SecGroupService/GetSgSubnets"
	// SecGroupServiceGetSecGroupForAddressProcedure is the fully-qualified name of the
	// SecGroupService's GetSecGroupForAddress RPC.
	SecGroupServiceGetSecGroupForAddressProcedure = "/hbf.v1.sgroups.SecGroupService/GetSecGroupForAddress"
	// SecGroupServiceGetSecGroupForHostProcedure is the fully-qualified name of the SecGroupService's
	// GetSecGroupForHost RPC.
	SecGroupServiceGetSecGroupForHostProcedure = "/hbf.v1.sgroups.SecGroupService/GetSecGroupForHost"
	// SecGroupServiceFindSgSgRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindSgSgRules RPC.
	SecGroupServiceFindSgSgRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindSgSgRules"
	// SecGroupServiceFindFqdnRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindFqdnRules RPC.
	SecGroupServiceFindFqdnRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindFqdnRules"
	// SecGroupServiceFindSgIcmpRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindSgIcmpRules RPC.
	SecGroupServiceFindSgIcmpRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindSgIcmpRules"
	// SecGroupServiceFindSgSgIcmpRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindSgSgIcmpRules RPC.
	SecGroupServiceFindSgSgIcmpRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindSgSgIcmpRules"
	// SecGroupServiceFindIECidrSgRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindIECidrSgRules RPC.
	SecGroupServiceFindIECidrSgRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindIECidrSgRules"
	// SecGroupServiceFindIESgSgRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindIESgSgRules RPC.
	SecGroupServiceFindIESgSgRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindIESgSgRules"
	// SecGroupServiceFindIESgSgIcmpRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindIESgSgIcmpRules RPC.
	SecGroupServiceFindIESgSgIcmpRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindIESgSgIcmpRules"
	// SecGroupServiceFindIECidrSgIcmpRulesProcedure is the fully-qualified name of the
	// SecGroupService's FindIECidrSgIcmpRules RPC.
	SecGroupServiceFindIECidrSgIcmpRulesProcedure = "/hbf.v1.sgroups.SecGroupService/FindIECidrSgIcmpRules"
	// SecGroupServiceUpdHostIPSetProcedure is the fully-qualified name of the SecGroupService's
	// UpdHostIPSet RPC.
	SecGroupServiceUpdHostIPSetProcedure = "/hbf.v1.sgroups.SecGroupService/UpdHostIPSet"
)

// SecGroupServiceClient is a client for the hbf.v1.sgroups.SecGroupService service.
type SecGroupServiceClient interface {
	Sync(context.Context, *connect.Request[v1.SyncReq]) (*connect.Response[empty.Empty], error)
	SyncStatus(context.Context, *connect.Request[empty.Empty]) (*connect.Response[v1.SyncStatusResp], error)
	SyncStatuses(context.Context, *connect.Request[empty.Empty]) (*connect.ServerStreamForClient[v1.SyncStatusResp], error)
	ListNetworks(context.Context, *connect.Request[v1.ListNetworksReq]) (*connect.Response[v1.ListNetworksResp], error)
	ListSecurityGroups(context.Context, *connect.Request[v1.ListSecurityGroupsReq]) (*connect.Response[v1.ListSecurityGroupsResp], error)
	ListHosts(context.Context, *connect.Request[v1.ListHostsReq]) (*connect.Response[v1.ListHostsResp], error)
	ListServices(context.Context, *connect.Request[v1.ListServicesReq]) (*connect.Response[v1.ListServicesResp], error)
	ListSvcSvcRules(context.Context, *connect.Request[v1.ListSvcSvcRulesReq]) (*connect.Response[v1.ListSvcSvcRulesResp], error)
	ListSvcFqdnRules(context.Context, *connect.Request[v1.ListSvcFqdnRulesReq]) (*connect.Response[v1.ListSvcFqdnRulesResp], error)
	GetSgSubnets(context.Context, *connect.Request[v1.GetSgSubnetsReq]) (*connect.Response[v1.GetSgSubnetsResp], error)
	GetSecGroupForAddress(context.Context, *connect.Request[v1.GetSecGroupForAddressReq]) (*connect.Response[v1.SecGroup], error)
	GetSecGroupForHost(context.Context, *connect.Request[v1.GetSecGroupForHostReq]) (*connect.Response[v1.SecGroup], error)
	FindSgSgRules(context.Context, *connect.Request[v1.FindSgSgRulesReq]) (*connect.Response[v1.SgSgRulesResp], error)
	FindFqdnRules(context.Context, *connect.Request[v1.FindFqdnRulesReq]) (*connect.Response[v1.FqdnRulesResp], error)
	FindSgIcmpRules(context.Context, *connect.Request[v1.FindSgIcmpRulesReq]) (*connect.Response[v1.SgIcmpRulesResp], error)
	FindSgSgIcmpRules(context.Context, *connect.Request[v1.FindSgSgIcmpRulesReq]) (*connect.Response[v1.SgSgIcmpRulesResp], error)
	FindIECidrSgRules(context.Context, *connect.Request[v1.FindIECidrSgRulesReq]) (*connect.Response[v1.IECidrSgRulesResp], error)
	FindIESgSgRules(context.Context, *connect.Request[v1.FindIESgSgRulesReq]) (*connect.Response[v1.IESgSgRulesResp], error)
	FindIESgSgIcmpRules(context.Context, *connect.Request[v1.FindIESgSgIcmpRulesReq]) (*connect.Response[v1.IESgSgIcmpRulesResp], error)
	FindIECidrSgIcmpRules(context.Context, *connect.Request[v1.FindIECidrSgIcmpRulesReq]) (*connect.Response[v1.IECidrSgIcmpRulesResp], error)
	UpdHostIPSet(context.Context, *connect.Request[v1.UpdHostIPSetReq]) (*connect.Response[empty.Empty], error)
}

// NewSecGroupServiceClient constructs a client for the hbf.v1.sgroups.SecGroupService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecGroupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecGroupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	secGroupServiceMethods := v1.File_sgroups_v1_service_proto.Services().ByName("SecGroupService").Methods()
	return &secGroupServiceClient{
		sync: connect.NewClient[v1.SyncReq, empty.Empty](
			httpClient,
			baseURL+SecGroupServiceSyncProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
		syncStatus: connect.NewClient[empty.Empty, v1.SyncStatusResp](
			httpClient,
			baseURL+SecGroupServiceSyncStatusProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("SyncStatus")),
			connect.WithClientOptions(opts...),
		),
		syncStatuses: connect.NewClient[empty.Empty, v1.SyncStatusResp](
			httpClient,
			baseURL+SecGroupServiceSyncStatusesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("SyncStatuses")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[v1.ListNetworksReq, v1.ListNetworksResp](
			httpClient,
			baseURL+SecGroupServiceListNetworksProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		listSecurityGroups: connect.NewClient[v1.ListSecurityGroupsReq, v1.ListSecurityGroupsResp](
			httpClient,
			baseURL+SecGroupServiceListSecurityGroupsProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListSecurityGroups")),
			connect.WithClientOptions(opts...),
		),
		listHosts: connect.NewClient[v1.ListHostsReq, v1.ListHostsResp](
			httpClient,
			baseURL+SecGroupServiceListHostsProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListHosts")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[v1.ListServicesReq, v1.ListServicesResp](
			httpClient,
			baseURL+SecGroupServiceListServicesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		listSvcSvcRules: connect.NewClient[v1.ListSvcSvcRulesReq, v1.ListSvcSvcRulesResp](
			httpClient,
			baseURL+SecGroupServiceListSvcSvcRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListSvcSvcRules")),
			connect.WithClientOptions(opts...),
		),
		listSvcFqdnRules: connect.NewClient[v1.ListSvcFqdnRulesReq, v1.ListSvcFqdnRulesResp](
			httpClient,
			baseURL+SecGroupServiceListSvcFqdnRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListSvcFqdnRules")),
			connect.WithClientOptions(opts...),
		),
		getSgSubnets: connect.NewClient[v1.GetSgSubnetsReq, v1.GetSgSubnetsResp](
			httpClient,
			baseURL+SecGroupServiceGetSgSubnetsProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("GetSgSubnets")),
			connect.WithClientOptions(opts...),
		),
		getSecGroupForAddress: connect.NewClient[v1.GetSecGroupForAddressReq, v1.SecGroup](
			httpClient,
			baseURL+SecGroupServiceGetSecGroupForAddressProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("GetSecGroupForAddress")),
			connect.WithClientOptions(opts...),
		),
		getSecGroupForHost: connect.NewClient[v1.GetSecGroupForHostReq, v1.SecGroup](
			httpClient,
			baseURL+SecGroupServiceGetSecGroupForHostProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("GetSecGroupForHost")),
			connect.WithClientOptions(opts...),
		),
		findSgSgRules: connect.NewClient[v1.FindSgSgRulesReq, v1.SgSgRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindSgSgRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgRules")),
			connect.WithClientOptions(opts...),
		),
		findFqdnRules: connect.NewClient[v1.FindFqdnRulesReq, v1.FqdnRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindFqdnRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindFqdnRules")),
			connect.WithClientOptions(opts...),
		),
		findSgIcmpRules: connect.NewClient[v1.FindSgIcmpRulesReq, v1.SgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		findSgSgIcmpRules: connect.NewClient[v1.FindSgSgIcmpRulesReq, v1.SgSgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindSgSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		findIECidrSgRules: connect.NewClient[v1.FindIECidrSgRulesReq, v1.IECidrSgRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIECidrSgRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgRules")),
			connect.WithClientOptions(opts...),
		),
		findIESgSgRules: connect.NewClient[v1.FindIESgSgRulesReq, v1.IESgSgRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIESgSgRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgRules")),
			connect.WithClientOptions(opts...),
		),
		findIESgSgIcmpRules: connect.NewClient[v1.FindIESgSgIcmpRulesReq, v1.IESgSgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIESgSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		findIECidrSgIcmpRules: connect.NewClient[v1.FindIECidrSgIcmpRulesReq, v1.IECidrSgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIECidrSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		updHostIPSet: connect.NewClient[v1.UpdHostIPSetReq, empty.Empty](
			httpClient,
			baseURL+SecGroupServiceUpdHostIPSetProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("UpdHostIPSet")),
			connect.WithClientOptions(opts...),
		),
	}
}

// secGroupServiceClient implements SecGroupServiceClient.
type secGroupServiceClient struct {
	sync                  *connect.Client[v1.SyncReq, empty.Empty]
	syncStatus            *connect.Client[empty.Empty, v1.SyncStatusResp]
	syncStatuses          *connect.Client[empty.Empty, v1.SyncStatusResp]
	listNetworks          *connect.Client[v1.ListNetworksReq, v1.ListNetworksResp]
	listSecurityGroups    *connect.Client[v1.ListSecurityGroupsReq, v1.ListSecurityGroupsResp]
	listHosts             *connect.Client[v1.ListHostsReq, v1.ListHostsResp]
	listServices          *connect.Client[v1.ListServicesReq, v1.ListServicesResp]
	listSvcSvcRules       *connect.Client[v1.ListSvcSvcRulesReq, v1.ListSvcSvcRulesResp]
	listSvcFqdnRules      *connect.Client[v1.ListSvcFqdnRulesReq, v1.ListSvcFqdnRulesResp]
	getSgSubnets          *connect.Client[v1.GetSgSubnetsReq, v1.GetSgSubnetsResp]
	getSecGroupForAddress *connect.Client[v1.GetSecGroupForAddressReq, v1.SecGroup]
	getSecGroupForHost    *connect.Client[v1.GetSecGroupForHostReq, v1.SecGroup]
	findSgSgRules         *connect.Client[v1.FindSgSgRulesReq, v1.SgSgRulesResp]
	findFqdnRules         *connect.Client[v1.FindFqdnRulesReq, v1.FqdnRulesResp]
	findSgIcmpRules       *connect.Client[v1.FindSgIcmpRulesReq, v1.SgIcmpRulesResp]
	findSgSgIcmpRules     *connect.Client[v1.FindSgSgIcmpRulesReq, v1.SgSgIcmpRulesResp]
	findIECidrSgRules     *connect.Client[v1.FindIECidrSgRulesReq, v1.IECidrSgRulesResp]
	findIESgSgRules       *connect.Client[v1.FindIESgSgRulesReq, v1.IESgSgRulesResp]
	findIESgSgIcmpRules   *connect.Client[v1.FindIESgSgIcmpRulesReq, v1.IESgSgIcmpRulesResp]
	findIECidrSgIcmpRules *connect.Client[v1.FindIECidrSgIcmpRulesReq, v1.IECidrSgIcmpRulesResp]
	updHostIPSet          *connect.Client[v1.UpdHostIPSetReq, empty.Empty]
}

// Sync calls hbf.v1.sgroups.SecGroupService.Sync.
func (c *secGroupServiceClient) Sync(ctx context.Context, req *connect.Request[v1.SyncReq]) (*connect.Response[empty.Empty], error) {
	return c.sync.CallUnary(ctx, req)
}

// SyncStatus calls hbf.v1.sgroups.SecGroupService.SyncStatus.
func (c *secGroupServiceClient) SyncStatus(ctx context.Context, req *connect.Request[empty.Empty]) (*connect.Response[v1.SyncStatusResp], error) {
	return c.syncStatus.CallUnary(ctx, req)
}

// SyncStatuses calls hbf.v1.sgroups.SecGroupService.SyncStatuses.
func (c *secGroupServiceClient) SyncStatuses(ctx context.Context, req *connect.Request[empty.Empty]) (*connect.ServerStreamForClient[v1.SyncStatusResp], error) {
	return c.syncStatuses.CallServerStream(ctx, req)
}

// ListNetworks calls hbf.v1.sgroups.SecGroupService.ListNetworks.
func (c *secGroupServiceClient) ListNetworks(ctx context.Context, req *connect.Request[v1.ListNetworksReq]) (*connect.Response[v1.ListNetworksResp], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// ListSecurityGroups calls hbf.v1.sgroups.SecGroupService.ListSecurityGroups.
func (c *secGroupServiceClient) ListSecurityGroups(ctx context.Context, req *connect.Request[v1.ListSecurityGroupsReq]) (*connect.Response[v1.ListSecurityGroupsResp], error) {
	return c.listSecurityGroups.CallUnary(ctx, req)
}

// ListHosts calls hbf.v1.sgroups.SecGroupService.ListHosts.
func (c *secGroupServiceClient) ListHosts(ctx context.Context, req *connect.Request[v1.ListHostsReq]) (*connect.Response[v1.ListHostsResp], error) {
	return c.listHosts.CallUnary(ctx, req)
}

// ListServices calls hbf.v1.sgroups.SecGroupService.ListServices.
func (c *secGroupServiceClient) ListServices(ctx context.Context, req *connect.Request[v1.ListServicesReq]) (*connect.Response[v1.ListServicesResp], error) {
	return c.listServices.CallUnary(ctx, req)
}

// ListSvcSvcRules calls hbf.v1.sgroups.SecGroupService.ListSvcSvcRules.
func (c *secGroupServiceClient) ListSvcSvcRules(ctx context.Context, req *connect.Request[v1.ListSvcSvcRulesReq]) (*connect.Response[v1.ListSvcSvcRulesResp], error) {
	return c.listSvcSvcRules.CallUnary(ctx, req)
}

// ListSvcFqdnRules calls hbf.v1.sgroups.SecGroupService.ListSvcFqdnRules.
func (c *secGroupServiceClient) ListSvcFqdnRules(ctx context.Context, req *connect.Request[v1.ListSvcFqdnRulesReq]) (*connect.Response[v1.ListSvcFqdnRulesResp], error) {
	return c.listSvcFqdnRules.CallUnary(ctx, req)
}

// GetSgSubnets calls hbf.v1.sgroups.SecGroupService.GetSgSubnets.
func (c *secGroupServiceClient) GetSgSubnets(ctx context.Context, req *connect.Request[v1.GetSgSubnetsReq]) (*connect.Response[v1.GetSgSubnetsResp], error) {
	return c.getSgSubnets.CallUnary(ctx, req)
}

// GetSecGroupForAddress calls hbf.v1.sgroups.SecGroupService.GetSecGroupForAddress.
func (c *secGroupServiceClient) GetSecGroupForAddress(ctx context.Context, req *connect.Request[v1.GetSecGroupForAddressReq]) (*connect.Response[v1.SecGroup], error) {
	return c.getSecGroupForAddress.CallUnary(ctx, req)
}

// GetSecGroupForHost calls hbf.v1.sgroups.SecGroupService.GetSecGroupForHost.
func (c *secGroupServiceClient) GetSecGroupForHost(ctx context.Context, req *connect.Request[v1.GetSecGroupForHostReq]) (*connect.Response[v1.SecGroup], error) {
	return c.getSecGroupForHost.CallUnary(ctx, req)
}

// FindSgSgRules calls hbf.v1.sgroups.SecGroupService.FindSgSgRules.
func (c *secGroupServiceClient) FindSgSgRules(ctx context.Context, req *connect.Request[v1.FindSgSgRulesReq]) (*connect.Response[v1.SgSgRulesResp], error) {
	return c.findSgSgRules.CallUnary(ctx, req)
}

// FindFqdnRules calls hbf.v1.sgroups.SecGroupService.FindFqdnRules.
func (c *secGroupServiceClient) FindFqdnRules(ctx context.Context, req *connect.Request[v1.FindFqdnRulesReq]) (*connect.Response[v1.FqdnRulesResp], error) {
	return c.findFqdnRules.CallUnary(ctx, req)
}

// FindSgIcmpRules calls hbf.v1.sgroups.SecGroupService.FindSgIcmpRules.
func (c *secGroupServiceClient) FindSgIcmpRules(ctx context.Context, req *connect.Request[v1.FindSgIcmpRulesReq]) (*connect.Response[v1.SgIcmpRulesResp], error) {
	return c.findSgIcmpRules.CallUnary(ctx, req)
}

// FindSgSgIcmpRules calls hbf.v1.sgroups.SecGroupService.FindSgSgIcmpRules.
func (c *secGroupServiceClient) FindSgSgIcmpRules(ctx context.Context, req *connect.Request[v1.FindSgSgIcmpRulesReq]) (*connect.Response[v1.SgSgIcmpRulesResp], error) {
	return c.findSgSgIcmpRules.CallUnary(ctx, req)
}

// FindIECidrSgRules calls hbf.v1.sgroups.SecGroupService.FindIECidrSgRules.
func (c *secGroupServiceClient) FindIECidrSgRules(ctx context.Context, req *connect.Request[v1.FindIECidrSgRulesReq]) (*connect.Response[v1.IECidrSgRulesResp], error) {
	return c.findIECidrSgRules.CallUnary(ctx, req)
}

// FindIESgSgRules calls hbf.v1.sgroups.SecGroupService.FindIESgSgRules.
func (c *secGroupServiceClient) FindIESgSgRules(ctx context.Context, req *connect.Request[v1.FindIESgSgRulesReq]) (*connect.Response[v1.IESgSgRulesResp], error) {
	return c.findIESgSgRules.CallUnary(ctx, req)
}

// FindIESgSgIcmpRules calls hbf.v1.sgroups.SecGroupService.FindIESgSgIcmpRules.
func (c *secGroupServiceClient) FindIESgSgIcmpRules(ctx context.Context, req *connect.Request[v1.FindIESgSgIcmpRulesReq]) (*connect.Response[v1.IESgSgIcmpRulesResp], error) {
	return c.findIESgSgIcmpRules.CallUnary(ctx, req)
}

// FindIECidrSgIcmpRules calls hbf.v1.sgroups.SecGroupService.FindIECidrSgIcmpRules.
func (c *secGroupServiceClient) FindIECidrSgIcmpRules(ctx context.Context, req *connect.Request[v1.FindIECidrSgIcmpRulesReq]) (*connect.Response[v1.IECidrSgIcmpRulesResp], error) {
	return c.findIECidrSgIcmpRules.CallUnary(ctx, req)
}

// UpdHostIPSet calls hbf.v1.sgroups.SecGroupService.UpdHostIPSet.
func (c *secGroupServiceClient) UpdHostIPSet(ctx context.Context, req *connect.Request[v1.UpdHostIPSetReq]) (*connect.Response[empty.Empty], error) {
	return c.updHostIPSet.CallUnary(ctx, req)
}

// SecGroupServiceHandler is an implementation of the hbf.v1.sgroups.SecGroupService service.
type SecGroupServiceHandler interface {
	Sync(context.Context, *connect.Request[v1.SyncReq]) (*connect.Response[empty.Empty], error)
	SyncStatus(context.Context, *connect.Request[empty.Empty]) (*connect.Response[v1.SyncStatusResp], error)
	SyncStatuses(context.Context, *connect.Request[empty.Empty], *connect.ServerStream[v1.SyncStatusResp]) error
	ListNetworks(context.Context, *connect.Request[v1.ListNetworksReq]) (*connect.Response[v1.ListNetworksResp], error)
	ListSecurityGroups(context.Context, *connect.Request[v1.ListSecurityGroupsReq]) (*connect.Response[v1.ListSecurityGroupsResp], error)
	ListHosts(context.Context, *connect.Request[v1.ListHostsReq]) (*connect.Response[v1.ListHostsResp], error)
	ListServices(context.Context, *connect.Request[v1.ListServicesReq]) (*connect.Response[v1.ListServicesResp], error)
	ListSvcSvcRules(context.Context, *connect.Request[v1.ListSvcSvcRulesReq]) (*connect.Response[v1.ListSvcSvcRulesResp], error)
	ListSvcFqdnRules(context.Context, *connect.Request[v1.ListSvcFqdnRulesReq]) (*connect.Response[v1.ListSvcFqdnRulesResp], error)
	GetSgSubnets(context.Context, *connect.Request[v1.GetSgSubnetsReq]) (*connect.Response[v1.GetSgSubnetsResp], error)
	GetSecGroupForAddress(context.Context, *connect.Request[v1.GetSecGroupForAddressReq]) (*connect.Response[v1.SecGroup], error)
	GetSecGroupForHost(context.Context, *connect.Request[v1.GetSecGroupForHostReq]) (*connect.Response[v1.SecGroup], error)
	FindSgSgRules(context.Context, *connect.Request[v1.FindSgSgRulesReq]) (*connect.Response[v1.SgSgRulesResp], error)
	FindFqdnRules(context.Context, *connect.Request[v1.FindFqdnRulesReq]) (*connect.Response[v1.FqdnRulesResp], error)
	FindSgIcmpRules(context.Context, *connect.Request[v1.FindSgIcmpRulesReq]) (*connect.Response[v1.SgIcmpRulesResp], error)
	FindSgSgIcmpRules(context.Context, *connect.Request[v1.FindSgSgIcmpRulesReq]) (*connect.Response[v1.SgSgIcmpRulesResp], error)
	FindIECidrSgRules(context.Context, *connect.Request[v1.FindIECidrSgRulesReq]) (*connect.Response[v1.IECidrSgRulesResp], error)
	FindIESgSgRules(context.Context, *connect.Request[v1.FindIESgSgRulesReq]) (*connect.Response[v1.IESgSgRulesResp], error)
	FindIESgSgIcmpRules(context.Context, *connect.Request[v1.FindIESgSgIcmpRulesReq]) (*connect.Response[v1.IESgSgIcmpRulesResp], error)
	FindIECidrSgIcmpRules(context.Context, *connect.Request[v1.FindIECidrSgIcmpRulesReq]) (*connect.Response[v1.IECidrSgIcmpRulesResp], error)
	UpdHostIPSet(context.Context, *connect.Request[v1.UpdHostIPSetReq]) (*connect.Response[empty.Empty], error)
}

// NewSecGroupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecGroupServiceHandler(svc SecGroupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secGroupServiceMethods := v1.File_sgroups_v1_service_proto.Services().ByName("SecGroupService").Methods()
	secGroupServiceSyncHandler := connect.NewUnaryHandler(
		SecGroupServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(secGroupServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceSyncStatusHandler := connect.NewUnaryHandler(
		SecGroupServiceSyncStatusProcedure,
		svc.SyncStatus,
		connect.WithSchema(secGroupServiceMethods.ByName("SyncStatus")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceSyncStatusesHandler := connect.NewServerStreamHandler(
		SecGroupServiceSyncStatusesProcedure,
		svc.SyncStatuses,
		connect.WithSchema(secGroupServiceMethods.ByName("SyncStatuses")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListNetworksHandler := connect.NewUnaryHandler(
		SecGroupServiceListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(secGroupServiceMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListSecurityGroupsHandler := connect.NewUnaryHandler(
		SecGroupServiceListSecurityGroupsProcedure,
		svc.ListSecurityGroups,
		connect.WithSchema(secGroupServiceMethods.ByName("ListSecurityGroups")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListHostsHandler := connect.NewUnaryHandler(
		SecGroupServiceListHostsProcedure,
		svc.ListHosts,
		connect.WithSchema(secGroupServiceMethods.ByName("ListHosts")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListServicesHandler := connect.NewUnaryHandler(
		SecGroupServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(secGroupServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListSvcSvcRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceListSvcSvcRulesProcedure,
		svc.ListSvcSvcRules,
		connect.WithSchema(secGroupServiceMethods.ByName("ListSvcSvcRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListSvcFqdnRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceListSvcFqdnRulesProcedure,
		svc.ListSvcFqdnRules,
		connect.WithSchema(secGroupServiceMethods.ByName("ListSvcFqdnRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceGetSgSubnetsHandler := connect.NewUnaryHandler(
		SecGroupServiceGetSgSubnetsProcedure,
		svc.GetSgSubnets,
		connect.WithSchema(secGroupServiceMethods.ByName("GetSgSubnets")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceGetSecGroupForAddressHandler := connect.NewUnaryHandler(
		SecGroupServiceGetSecGroupForAddressProcedure,
		svc.GetSecGroupForAddress,
		connect.WithSchema(secGroupServiceMethods.ByName("GetSecGroupForAddress")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceGetSecGroupForHostHandler := connect.NewUnaryHandler(
		SecGroupServiceGetSecGroupForHostProcedure,
		svc.GetSecGroupForHost,
		connect.WithSchema(secGroupServiceMethods.ByName("GetSecGroupForHost")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindSgSgRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindSgSgRulesProcedure,
		svc.FindSgSgRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindFqdnRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindFqdnRulesProcedure,
		svc.FindFqdnRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindFqdnRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindSgIcmpRulesProcedure,
		svc.FindSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindSgSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindSgSgIcmpRulesProcedure,
		svc.FindSgSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIECidrSgRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIECidrSgRulesProcedure,
		svc.FindIECidrSgRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIESgSgRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIESgSgRulesProcedure,
		svc.FindIESgSgRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIESgSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIESgSgIcmpRulesProcedure,
		svc.FindIESgSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIECidrSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIECidrSgIcmpRulesProcedure,
		svc.FindIECidrSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceUpdHostIPSetHandler := connect.NewUnaryHandler(
		SecGroupServiceUpdHostIPSetProcedure,
		svc.UpdHostIPSet,
		connect.WithSchema(secGroupServiceMethods.ByName("UpdHostIPSet")),
		connect.WithHandlerOptions(opts...),
	)
	return "/hbf.v1.sgroups.SecGroupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecGroupServiceSyncProcedure:
			secGroupServiceSyncHandler.ServeHTTP(w, r)
		case SecGroupServiceSyncStatusProcedure:
			secGroupServiceSyncStatusHandler.ServeHTTP(w, r)
		case SecGroupServiceSyncStatusesProcedure:
			secGroupServiceSyncStatusesHandler.ServeHTTP(w, r)
		case SecGroupServiceListNetworksProcedure:
			secGroupServiceListNetworksHandler.ServeHTTP(w, r)
		case SecGroupServiceListSecurityGroupsProcedure:
			secGroupServiceListSecurityGroupsHandler.ServeHTTP(w, r)
		case SecGroupServiceListHostsProcedure:
			secGroupServiceListHostsHandler.ServeHTTP(w, r)
		case SecGroupServiceListServicesProcedure:
			secGroupServiceListServicesHandler.ServeHTTP(w, r)
		case SecGroupServiceListSvcSvcRulesProcedure:
			secGroupServiceListSvcSvcRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceListSvcFqdnRulesProcedure:
			secGroupServiceListSvcFqdnRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceGetSgSubnetsProcedure:
			secGroupServiceGetSgSubnetsHandler.ServeHTTP(w, r)
		case SecGroupServiceGetSecGroupForAddressProcedure:
			secGroupServiceGetSecGroupForAddressHandler.ServeHTTP(w, r)
		case SecGroupServiceGetSecGroupForHostProcedure:
			secGroupServiceGetSecGroupForHostHandler.ServeHTTP(w, r)
		case SecGroupServiceFindSgSgRulesProcedure:
			secGroupServiceFindSgSgRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindFqdnRulesProcedure:
			secGroupServiceFindFqdnRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindSgIcmpRulesProcedure:
			secGroupServiceFindSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindSgSgIcmpRulesProcedure:
			secGroupServiceFindSgSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIECidrSgRulesProcedure:
			secGroupServiceFindIECidrSgRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIESgSgRulesProcedure:
			secGroupServiceFindIESgSgRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIESgSgIcmpRulesProcedure:
			secGroupServiceFindIESgSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIECidrSgIcmpRulesProcedure:
			secGroupServiceFindIECidrSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceUpdHostIPSetProcedure:
			secGroupServiceUpdHostIPSetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecGroupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecGroupServiceHandler struct{}

func (UnimplementedSecGroupServiceHandler) Sync(context.Context, *connect.Request[v1.SyncReq]) (*connect.Response[empty.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.Sync is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) SyncStatus(context.Context, *connect.Request[empty.Empty]) (*connect.Response[v1.SyncStatusResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.SyncStatus is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) SyncStatuses(context.Context, *connect.Request[empty.Empty], *connect.ServerStream[v1.SyncStatusResp]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.SyncStatuses is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListNetworks(context.Context, *connect.Request[v1.ListNetworksReq]) (*connect.Response[v1.ListNetworksResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.ListNetworks is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListSecurityGroups(context.Context, *connect.Request[v1.ListSecurityGroupsReq]) (*connect.Response[v1.ListSecurityGroupsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.ListSecurityGroups is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListHosts(context.Context, *connect.Request[v1.ListHostsReq]) (*connect.Response[v1.ListHostsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.ListHosts is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListServices(context.Context, *connect.Request[v1.ListServicesReq]) (*connect.Response[v1.ListServicesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.ListServices is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListSvcSvcRules(context.Context, *connect.Request[v1.ListSvcSvcRulesReq]) (*connect.Response[v1.ListSvcSvcRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.ListSvcSvcRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListSvcFqdnRules(context.Context, *connect.Request[v1.ListSvcFqdnRulesReq]) (*connect.Response[v1.ListSvcFqdnRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.ListSvcFqdnRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) GetSgSubnets(context.Context, *connect.Request[v1.GetSgSubnetsReq]) (*connect.Response[v1.GetSgSubnetsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.GetSgSubnets is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) GetSecGroupForAddress(context.Context, *connect.Request[v1.GetSecGroupForAddressReq]) (*connect.Response[v1.SecGroup], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.GetSecGroupForAddress is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) GetSecGroupForHost(context.Context, *connect.Request[v1.GetSecGroupForHostReq]) (*connect.Response[v1.SecGroup], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.GetSecGroupForHost is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindSgSgRules(context.Context, *connect.Request[v1.FindSgSgRulesReq]) (*connect.Response[v1.SgSgRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindSgSgRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindFqdnRules(context.Context, *connect.Request[v1.FindFqdnRulesReq]) (*connect.Response[v1.FqdnRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindFqdnRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindSgIcmpRules(context.Context, *connect.Request[v1.FindSgIcmpRulesReq]) (*connect.Response[v1.SgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindSgSgIcmpRules(context.Context, *connect.Request[v1.FindSgSgIcmpRulesReq]) (*connect.Response[v1.SgSgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindSgSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIECidrSgRules(context.Context, *connect.Request[v1.FindIECidrSgRulesReq]) (*connect.Response[v1.IECidrSgRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindIECidrSgRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIESgSgRules(context.Context, *connect.Request[v1.FindIESgSgRulesReq]) (*connect.Response[v1.IESgSgRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindIESgSgRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIESgSgIcmpRules(context.Context, *connect.Request[v1.FindIESgSgIcmpRulesReq]) (*connect.Response[v1.IESgSgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindIESgSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIECidrSgIcmpRules(context.Context, *connect.Request[v1.FindIECidrSgIcmpRulesReq]) (*connect.Response[v1.IECidrSgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.FindIECidrSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) UpdHostIPSet(context.Context, *connect.Request[v1.UpdHostIPSetReq]) (*connect.Response[empty.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v1.sgroups.SecGroupService.UpdHostIPSet is not implemented"))
}
