// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sgroups/api.proto

package sgroupsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	sgroups "github.com/H-BF/protos/pkg/api/sgroups"
	empty "github.com/golang/protobuf/ptypes/empty"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SecGroupServiceName is the fully-qualified name of the SecGroupService service.
	SecGroupServiceName = "hbf.v2.sgroups.SecGroupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecGroupServiceSyncProcedure is the fully-qualified name of the SecGroupService's Sync RPC.
	SecGroupServiceSyncProcedure = "/hbf.v2.sgroups.SecGroupService/Sync"
	// SecGroupServiceSyncStatusProcedure is the fully-qualified name of the SecGroupService's
	// SyncStatus RPC.
	SecGroupServiceSyncStatusProcedure = "/hbf.v2.sgroups.SecGroupService/SyncStatus"
	// SecGroupServiceSyncStatusesProcedure is the fully-qualified name of the SecGroupService's
	// SyncStatuses RPC.
	SecGroupServiceSyncStatusesProcedure = "/hbf.v2.sgroups.SecGroupService/SyncStatuses"
	// SecGroupServiceListNetworksProcedure is the fully-qualified name of the SecGroupService's
	// ListNetworks RPC.
	SecGroupServiceListNetworksProcedure = "/hbf.v2.sgroups.SecGroupService/ListNetworks"
	// SecGroupServiceListSecurityGroupsProcedure is the fully-qualified name of the SecGroupService's
	// ListSecurityGroups RPC.
	SecGroupServiceListSecurityGroupsProcedure = "/hbf.v2.sgroups.SecGroupService/ListSecurityGroups"
	// SecGroupServiceGetSgSubnetsProcedure is the fully-qualified name of the SecGroupService's
	// GetSgSubnets RPC.
	SecGroupServiceGetSgSubnetsProcedure = "/hbf.v2.sgroups.SecGroupService/GetSgSubnets"
	// SecGroupServiceFindSgSgRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindSgSgRules RPC.
	SecGroupServiceFindSgSgRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindSgSgRules"
	// SecGroupServiceFindFqdnRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindFqdnRules RPC.
	SecGroupServiceFindFqdnRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindFqdnRules"
	// SecGroupServiceFindSgIcmpRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindSgIcmpRules RPC.
	SecGroupServiceFindSgIcmpRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindSgIcmpRules"
	// SecGroupServiceFindSgSgIcmpRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindSgSgIcmpRules RPC.
	SecGroupServiceFindSgSgIcmpRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindSgSgIcmpRules"
	// SecGroupServiceFindIECidrSgRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindIECidrSgRules RPC.
	SecGroupServiceFindIECidrSgRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindIECidrSgRules"
	// SecGroupServiceFindIESgSgRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindIESgSgRules RPC.
	SecGroupServiceFindIESgSgRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindIESgSgRules"
	// SecGroupServiceFindIESgSgIcmpRulesProcedure is the fully-qualified name of the SecGroupService's
	// FindIESgSgIcmpRules RPC.
	SecGroupServiceFindIESgSgIcmpRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindIESgSgIcmpRules"
	// SecGroupServiceFindIECidrSgIcmpRulesProcedure is the fully-qualified name of the
	// SecGroupService's FindIECidrSgIcmpRules RPC.
	SecGroupServiceFindIECidrSgIcmpRulesProcedure = "/hbf.v2.sgroups.SecGroupService/FindIECidrSgIcmpRules"
	// SecGroupServiceGetSecGroupForAddressProcedure is the fully-qualified name of the
	// SecGroupService's GetSecGroupForAddress RPC.
	SecGroupServiceGetSecGroupForAddressProcedure = "/hbf.v2.sgroups.SecGroupService/GetSecGroupForAddress"
	// SecGroupServiceFindHostsProcedure is the fully-qualified name of the SecGroupService's FindHosts
	// RPC.
	SecGroupServiceFindHostsProcedure = "/hbf.v2.sgroups.SecGroupService/FindHosts"
	// SecGroupServiceRegisterHostProcedure is the fully-qualified name of the SecGroupService's
	// RegisterHost RPC.
	SecGroupServiceRegisterHostProcedure = "/hbf.v2.sgroups.SecGroupService/RegisterHost"
	// SecGroupServiceUpdateHostIPsetProcedure is the fully-qualified name of the SecGroupService's
	// UpdateHostIPset RPC.
	SecGroupServiceUpdateHostIPsetProcedure = "/hbf.v2.sgroups.SecGroupService/UpdateHostIPset"
	// SecGroupServiceDeleteHostProcedure is the fully-qualified name of the SecGroupService's
	// DeleteHost RPC.
	SecGroupServiceDeleteHostProcedure = "/hbf.v2.sgroups.SecGroupService/DeleteHost"
)

// SecGroupServiceClient is a client for the hbf.v2.sgroups.SecGroupService service.
type SecGroupServiceClient interface {
	Sync(context.Context, *connect.Request[sgroups.SyncReq]) (*connect.Response[empty.Empty], error)
	SyncStatus(context.Context, *connect.Request[empty.Empty]) (*connect.Response[sgroups.SyncStatusResp], error)
	SyncStatuses(context.Context, *connect.Request[empty.Empty]) (*connect.ServerStreamForClient[sgroups.SyncStatusResp], error)
	ListNetworks(context.Context, *connect.Request[sgroups.ListNetworksReq]) (*connect.Response[sgroups.ListNetworksResp], error)
	ListSecurityGroups(context.Context, *connect.Request[sgroups.ListSecurityGroupsReq]) (*connect.Response[sgroups.ListSecurityGroupsResp], error)
	GetSgSubnets(context.Context, *connect.Request[sgroups.GetSgSubnetsReq]) (*connect.Response[sgroups.GetSgSubnetsResp], error)
	FindSgSgRules(context.Context, *connect.Request[sgroups.FindSgSgRulesReq]) (*connect.Response[sgroups.SgSgRulesResp], error)
	FindFqdnRules(context.Context, *connect.Request[sgroups.FindFqdnRulesReq]) (*connect.Response[sgroups.FqdnRulesResp], error)
	FindSgIcmpRules(context.Context, *connect.Request[sgroups.FindSgIcmpRulesReq]) (*connect.Response[sgroups.SgIcmpRulesResp], error)
	FindSgSgIcmpRules(context.Context, *connect.Request[sgroups.FindSgSgIcmpRulesReq]) (*connect.Response[sgroups.SgSgIcmpRulesResp], error)
	FindIECidrSgRules(context.Context, *connect.Request[sgroups.FindIECidrSgRulesReq]) (*connect.Response[sgroups.IECidrSgRulesResp], error)
	FindIESgSgRules(context.Context, *connect.Request[sgroups.FindIESgSgRulesReq]) (*connect.Response[sgroups.IESgSgRulesResp], error)
	FindIESgSgIcmpRules(context.Context, *connect.Request[sgroups.FindIESgSgIcmpRulesReq]) (*connect.Response[sgroups.IESgSgIcmpRulesResp], error)
	FindIECidrSgIcmpRules(context.Context, *connect.Request[sgroups.FindIECidrSgIcmpRulesReq]) (*connect.Response[sgroups.IECidrSgIcmpRulesResp], error)
	GetSecGroupForAddress(context.Context, *connect.Request[sgroups.GetSecGroupForAddressReq]) (*connect.Response[sgroups.SecGroup], error)
	FindHosts(context.Context, *connect.Request[sgroups.FindHostsReq]) (*connect.Response[sgroups.HostList], error)
	RegisterHost(context.Context, *connect.Request[sgroups.RegisterHostReq]) (*connect.Response[empty.Empty], error)
	UpdateHostIPset(context.Context, *connect.Request[sgroups.UpdateHostIPReq]) (*connect.Response[empty.Empty], error)
	DeleteHost(context.Context, *connect.Request[sgroups.DeleteHostReq]) (*connect.Response[empty.Empty], error)
}

// NewSecGroupServiceClient constructs a client for the hbf.v2.sgroups.SecGroupService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecGroupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecGroupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	secGroupServiceMethods := sgroups.File_sgroups_api_proto.Services().ByName("SecGroupService").Methods()
	return &secGroupServiceClient{
		sync: connect.NewClient[sgroups.SyncReq, empty.Empty](
			httpClient,
			baseURL+SecGroupServiceSyncProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
		syncStatus: connect.NewClient[empty.Empty, sgroups.SyncStatusResp](
			httpClient,
			baseURL+SecGroupServiceSyncStatusProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("SyncStatus")),
			connect.WithClientOptions(opts...),
		),
		syncStatuses: connect.NewClient[empty.Empty, sgroups.SyncStatusResp](
			httpClient,
			baseURL+SecGroupServiceSyncStatusesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("SyncStatuses")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[sgroups.ListNetworksReq, sgroups.ListNetworksResp](
			httpClient,
			baseURL+SecGroupServiceListNetworksProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		listSecurityGroups: connect.NewClient[sgroups.ListSecurityGroupsReq, sgroups.ListSecurityGroupsResp](
			httpClient,
			baseURL+SecGroupServiceListSecurityGroupsProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("ListSecurityGroups")),
			connect.WithClientOptions(opts...),
		),
		getSgSubnets: connect.NewClient[sgroups.GetSgSubnetsReq, sgroups.GetSgSubnetsResp](
			httpClient,
			baseURL+SecGroupServiceGetSgSubnetsProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("GetSgSubnets")),
			connect.WithClientOptions(opts...),
		),
		findSgSgRules: connect.NewClient[sgroups.FindSgSgRulesReq, sgroups.SgSgRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindSgSgRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgRules")),
			connect.WithClientOptions(opts...),
		),
		findFqdnRules: connect.NewClient[sgroups.FindFqdnRulesReq, sgroups.FqdnRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindFqdnRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindFqdnRules")),
			connect.WithClientOptions(opts...),
		),
		findSgIcmpRules: connect.NewClient[sgroups.FindSgIcmpRulesReq, sgroups.SgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		findSgSgIcmpRules: connect.NewClient[sgroups.FindSgSgIcmpRulesReq, sgroups.SgSgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindSgSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		findIECidrSgRules: connect.NewClient[sgroups.FindIECidrSgRulesReq, sgroups.IECidrSgRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIECidrSgRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgRules")),
			connect.WithClientOptions(opts...),
		),
		findIESgSgRules: connect.NewClient[sgroups.FindIESgSgRulesReq, sgroups.IESgSgRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIESgSgRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgRules")),
			connect.WithClientOptions(opts...),
		),
		findIESgSgIcmpRules: connect.NewClient[sgroups.FindIESgSgIcmpRulesReq, sgroups.IESgSgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIESgSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		findIECidrSgIcmpRules: connect.NewClient[sgroups.FindIECidrSgIcmpRulesReq, sgroups.IECidrSgIcmpRulesResp](
			httpClient,
			baseURL+SecGroupServiceFindIECidrSgIcmpRulesProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgIcmpRules")),
			connect.WithClientOptions(opts...),
		),
		getSecGroupForAddress: connect.NewClient[sgroups.GetSecGroupForAddressReq, sgroups.SecGroup](
			httpClient,
			baseURL+SecGroupServiceGetSecGroupForAddressProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("GetSecGroupForAddress")),
			connect.WithClientOptions(opts...),
		),
		findHosts: connect.NewClient[sgroups.FindHostsReq, sgroups.HostList](
			httpClient,
			baseURL+SecGroupServiceFindHostsProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("FindHosts")),
			connect.WithClientOptions(opts...),
		),
		registerHost: connect.NewClient[sgroups.RegisterHostReq, empty.Empty](
			httpClient,
			baseURL+SecGroupServiceRegisterHostProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("RegisterHost")),
			connect.WithClientOptions(opts...),
		),
		updateHostIPset: connect.NewClient[sgroups.UpdateHostIPReq, empty.Empty](
			httpClient,
			baseURL+SecGroupServiceUpdateHostIPsetProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("UpdateHostIPset")),
			connect.WithClientOptions(opts...),
		),
		deleteHost: connect.NewClient[sgroups.DeleteHostReq, empty.Empty](
			httpClient,
			baseURL+SecGroupServiceDeleteHostProcedure,
			connect.WithSchema(secGroupServiceMethods.ByName("DeleteHost")),
			connect.WithClientOptions(opts...),
		),
	}
}

// secGroupServiceClient implements SecGroupServiceClient.
type secGroupServiceClient struct {
	sync                  *connect.Client[sgroups.SyncReq, empty.Empty]
	syncStatus            *connect.Client[empty.Empty, sgroups.SyncStatusResp]
	syncStatuses          *connect.Client[empty.Empty, sgroups.SyncStatusResp]
	listNetworks          *connect.Client[sgroups.ListNetworksReq, sgroups.ListNetworksResp]
	listSecurityGroups    *connect.Client[sgroups.ListSecurityGroupsReq, sgroups.ListSecurityGroupsResp]
	getSgSubnets          *connect.Client[sgroups.GetSgSubnetsReq, sgroups.GetSgSubnetsResp]
	findSgSgRules         *connect.Client[sgroups.FindSgSgRulesReq, sgroups.SgSgRulesResp]
	findFqdnRules         *connect.Client[sgroups.FindFqdnRulesReq, sgroups.FqdnRulesResp]
	findSgIcmpRules       *connect.Client[sgroups.FindSgIcmpRulesReq, sgroups.SgIcmpRulesResp]
	findSgSgIcmpRules     *connect.Client[sgroups.FindSgSgIcmpRulesReq, sgroups.SgSgIcmpRulesResp]
	findIECidrSgRules     *connect.Client[sgroups.FindIECidrSgRulesReq, sgroups.IECidrSgRulesResp]
	findIESgSgRules       *connect.Client[sgroups.FindIESgSgRulesReq, sgroups.IESgSgRulesResp]
	findIESgSgIcmpRules   *connect.Client[sgroups.FindIESgSgIcmpRulesReq, sgroups.IESgSgIcmpRulesResp]
	findIECidrSgIcmpRules *connect.Client[sgroups.FindIECidrSgIcmpRulesReq, sgroups.IECidrSgIcmpRulesResp]
	getSecGroupForAddress *connect.Client[sgroups.GetSecGroupForAddressReq, sgroups.SecGroup]
	findHosts             *connect.Client[sgroups.FindHostsReq, sgroups.HostList]
	registerHost          *connect.Client[sgroups.RegisterHostReq, empty.Empty]
	updateHostIPset       *connect.Client[sgroups.UpdateHostIPReq, empty.Empty]
	deleteHost            *connect.Client[sgroups.DeleteHostReq, empty.Empty]
}

// Sync calls hbf.v2.sgroups.SecGroupService.Sync.
func (c *secGroupServiceClient) Sync(ctx context.Context, req *connect.Request[sgroups.SyncReq]) (*connect.Response[empty.Empty], error) {
	return c.sync.CallUnary(ctx, req)
}

// SyncStatus calls hbf.v2.sgroups.SecGroupService.SyncStatus.
func (c *secGroupServiceClient) SyncStatus(ctx context.Context, req *connect.Request[empty.Empty]) (*connect.Response[sgroups.SyncStatusResp], error) {
	return c.syncStatus.CallUnary(ctx, req)
}

// SyncStatuses calls hbf.v2.sgroups.SecGroupService.SyncStatuses.
func (c *secGroupServiceClient) SyncStatuses(ctx context.Context, req *connect.Request[empty.Empty]) (*connect.ServerStreamForClient[sgroups.SyncStatusResp], error) {
	return c.syncStatuses.CallServerStream(ctx, req)
}

// ListNetworks calls hbf.v2.sgroups.SecGroupService.ListNetworks.
func (c *secGroupServiceClient) ListNetworks(ctx context.Context, req *connect.Request[sgroups.ListNetworksReq]) (*connect.Response[sgroups.ListNetworksResp], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// ListSecurityGroups calls hbf.v2.sgroups.SecGroupService.ListSecurityGroups.
func (c *secGroupServiceClient) ListSecurityGroups(ctx context.Context, req *connect.Request[sgroups.ListSecurityGroupsReq]) (*connect.Response[sgroups.ListSecurityGroupsResp], error) {
	return c.listSecurityGroups.CallUnary(ctx, req)
}

// GetSgSubnets calls hbf.v2.sgroups.SecGroupService.GetSgSubnets.
func (c *secGroupServiceClient) GetSgSubnets(ctx context.Context, req *connect.Request[sgroups.GetSgSubnetsReq]) (*connect.Response[sgroups.GetSgSubnetsResp], error) {
	return c.getSgSubnets.CallUnary(ctx, req)
}

// FindSgSgRules calls hbf.v2.sgroups.SecGroupService.FindSgSgRules.
func (c *secGroupServiceClient) FindSgSgRules(ctx context.Context, req *connect.Request[sgroups.FindSgSgRulesReq]) (*connect.Response[sgroups.SgSgRulesResp], error) {
	return c.findSgSgRules.CallUnary(ctx, req)
}

// FindFqdnRules calls hbf.v2.sgroups.SecGroupService.FindFqdnRules.
func (c *secGroupServiceClient) FindFqdnRules(ctx context.Context, req *connect.Request[sgroups.FindFqdnRulesReq]) (*connect.Response[sgroups.FqdnRulesResp], error) {
	return c.findFqdnRules.CallUnary(ctx, req)
}

// FindSgIcmpRules calls hbf.v2.sgroups.SecGroupService.FindSgIcmpRules.
func (c *secGroupServiceClient) FindSgIcmpRules(ctx context.Context, req *connect.Request[sgroups.FindSgIcmpRulesReq]) (*connect.Response[sgroups.SgIcmpRulesResp], error) {
	return c.findSgIcmpRules.CallUnary(ctx, req)
}

// FindSgSgIcmpRules calls hbf.v2.sgroups.SecGroupService.FindSgSgIcmpRules.
func (c *secGroupServiceClient) FindSgSgIcmpRules(ctx context.Context, req *connect.Request[sgroups.FindSgSgIcmpRulesReq]) (*connect.Response[sgroups.SgSgIcmpRulesResp], error) {
	return c.findSgSgIcmpRules.CallUnary(ctx, req)
}

// FindIECidrSgRules calls hbf.v2.sgroups.SecGroupService.FindIECidrSgRules.
func (c *secGroupServiceClient) FindIECidrSgRules(ctx context.Context, req *connect.Request[sgroups.FindIECidrSgRulesReq]) (*connect.Response[sgroups.IECidrSgRulesResp], error) {
	return c.findIECidrSgRules.CallUnary(ctx, req)
}

// FindIESgSgRules calls hbf.v2.sgroups.SecGroupService.FindIESgSgRules.
func (c *secGroupServiceClient) FindIESgSgRules(ctx context.Context, req *connect.Request[sgroups.FindIESgSgRulesReq]) (*connect.Response[sgroups.IESgSgRulesResp], error) {
	return c.findIESgSgRules.CallUnary(ctx, req)
}

// FindIESgSgIcmpRules calls hbf.v2.sgroups.SecGroupService.FindIESgSgIcmpRules.
func (c *secGroupServiceClient) FindIESgSgIcmpRules(ctx context.Context, req *connect.Request[sgroups.FindIESgSgIcmpRulesReq]) (*connect.Response[sgroups.IESgSgIcmpRulesResp], error) {
	return c.findIESgSgIcmpRules.CallUnary(ctx, req)
}

// FindIECidrSgIcmpRules calls hbf.v2.sgroups.SecGroupService.FindIECidrSgIcmpRules.
func (c *secGroupServiceClient) FindIECidrSgIcmpRules(ctx context.Context, req *connect.Request[sgroups.FindIECidrSgIcmpRulesReq]) (*connect.Response[sgroups.IECidrSgIcmpRulesResp], error) {
	return c.findIECidrSgIcmpRules.CallUnary(ctx, req)
}

// GetSecGroupForAddress calls hbf.v2.sgroups.SecGroupService.GetSecGroupForAddress.
func (c *secGroupServiceClient) GetSecGroupForAddress(ctx context.Context, req *connect.Request[sgroups.GetSecGroupForAddressReq]) (*connect.Response[sgroups.SecGroup], error) {
	return c.getSecGroupForAddress.CallUnary(ctx, req)
}

// FindHosts calls hbf.v2.sgroups.SecGroupService.FindHosts.
func (c *secGroupServiceClient) FindHosts(ctx context.Context, req *connect.Request[sgroups.FindHostsReq]) (*connect.Response[sgroups.HostList], error) {
	return c.findHosts.CallUnary(ctx, req)
}

// RegisterHost calls hbf.v2.sgroups.SecGroupService.RegisterHost.
func (c *secGroupServiceClient) RegisterHost(ctx context.Context, req *connect.Request[sgroups.RegisterHostReq]) (*connect.Response[empty.Empty], error) {
	return c.registerHost.CallUnary(ctx, req)
}

// UpdateHostIPset calls hbf.v2.sgroups.SecGroupService.UpdateHostIPset.
func (c *secGroupServiceClient) UpdateHostIPset(ctx context.Context, req *connect.Request[sgroups.UpdateHostIPReq]) (*connect.Response[empty.Empty], error) {
	return c.updateHostIPset.CallUnary(ctx, req)
}

// DeleteHost calls hbf.v2.sgroups.SecGroupService.DeleteHost.
func (c *secGroupServiceClient) DeleteHost(ctx context.Context, req *connect.Request[sgroups.DeleteHostReq]) (*connect.Response[empty.Empty], error) {
	return c.deleteHost.CallUnary(ctx, req)
}

// SecGroupServiceHandler is an implementation of the hbf.v2.sgroups.SecGroupService service.
type SecGroupServiceHandler interface {
	Sync(context.Context, *connect.Request[sgroups.SyncReq]) (*connect.Response[empty.Empty], error)
	SyncStatus(context.Context, *connect.Request[empty.Empty]) (*connect.Response[sgroups.SyncStatusResp], error)
	SyncStatuses(context.Context, *connect.Request[empty.Empty], *connect.ServerStream[sgroups.SyncStatusResp]) error
	ListNetworks(context.Context, *connect.Request[sgroups.ListNetworksReq]) (*connect.Response[sgroups.ListNetworksResp], error)
	ListSecurityGroups(context.Context, *connect.Request[sgroups.ListSecurityGroupsReq]) (*connect.Response[sgroups.ListSecurityGroupsResp], error)
	GetSgSubnets(context.Context, *connect.Request[sgroups.GetSgSubnetsReq]) (*connect.Response[sgroups.GetSgSubnetsResp], error)
	FindSgSgRules(context.Context, *connect.Request[sgroups.FindSgSgRulesReq]) (*connect.Response[sgroups.SgSgRulesResp], error)
	FindFqdnRules(context.Context, *connect.Request[sgroups.FindFqdnRulesReq]) (*connect.Response[sgroups.FqdnRulesResp], error)
	FindSgIcmpRules(context.Context, *connect.Request[sgroups.FindSgIcmpRulesReq]) (*connect.Response[sgroups.SgIcmpRulesResp], error)
	FindSgSgIcmpRules(context.Context, *connect.Request[sgroups.FindSgSgIcmpRulesReq]) (*connect.Response[sgroups.SgSgIcmpRulesResp], error)
	FindIECidrSgRules(context.Context, *connect.Request[sgroups.FindIECidrSgRulesReq]) (*connect.Response[sgroups.IECidrSgRulesResp], error)
	FindIESgSgRules(context.Context, *connect.Request[sgroups.FindIESgSgRulesReq]) (*connect.Response[sgroups.IESgSgRulesResp], error)
	FindIESgSgIcmpRules(context.Context, *connect.Request[sgroups.FindIESgSgIcmpRulesReq]) (*connect.Response[sgroups.IESgSgIcmpRulesResp], error)
	FindIECidrSgIcmpRules(context.Context, *connect.Request[sgroups.FindIECidrSgIcmpRulesReq]) (*connect.Response[sgroups.IECidrSgIcmpRulesResp], error)
	GetSecGroupForAddress(context.Context, *connect.Request[sgroups.GetSecGroupForAddressReq]) (*connect.Response[sgroups.SecGroup], error)
	FindHosts(context.Context, *connect.Request[sgroups.FindHostsReq]) (*connect.Response[sgroups.HostList], error)
	RegisterHost(context.Context, *connect.Request[sgroups.RegisterHostReq]) (*connect.Response[empty.Empty], error)
	UpdateHostIPset(context.Context, *connect.Request[sgroups.UpdateHostIPReq]) (*connect.Response[empty.Empty], error)
	DeleteHost(context.Context, *connect.Request[sgroups.DeleteHostReq]) (*connect.Response[empty.Empty], error)
}

// NewSecGroupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecGroupServiceHandler(svc SecGroupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secGroupServiceMethods := sgroups.File_sgroups_api_proto.Services().ByName("SecGroupService").Methods()
	secGroupServiceSyncHandler := connect.NewUnaryHandler(
		SecGroupServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(secGroupServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceSyncStatusHandler := connect.NewUnaryHandler(
		SecGroupServiceSyncStatusProcedure,
		svc.SyncStatus,
		connect.WithSchema(secGroupServiceMethods.ByName("SyncStatus")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceSyncStatusesHandler := connect.NewServerStreamHandler(
		SecGroupServiceSyncStatusesProcedure,
		svc.SyncStatuses,
		connect.WithSchema(secGroupServiceMethods.ByName("SyncStatuses")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListNetworksHandler := connect.NewUnaryHandler(
		SecGroupServiceListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(secGroupServiceMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceListSecurityGroupsHandler := connect.NewUnaryHandler(
		SecGroupServiceListSecurityGroupsProcedure,
		svc.ListSecurityGroups,
		connect.WithSchema(secGroupServiceMethods.ByName("ListSecurityGroups")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceGetSgSubnetsHandler := connect.NewUnaryHandler(
		SecGroupServiceGetSgSubnetsProcedure,
		svc.GetSgSubnets,
		connect.WithSchema(secGroupServiceMethods.ByName("GetSgSubnets")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindSgSgRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindSgSgRulesProcedure,
		svc.FindSgSgRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindFqdnRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindFqdnRulesProcedure,
		svc.FindFqdnRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindFqdnRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindSgIcmpRulesProcedure,
		svc.FindSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindSgSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindSgSgIcmpRulesProcedure,
		svc.FindSgSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindSgSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIECidrSgRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIECidrSgRulesProcedure,
		svc.FindIECidrSgRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIESgSgRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIESgSgRulesProcedure,
		svc.FindIESgSgRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIESgSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIESgSgIcmpRulesProcedure,
		svc.FindIESgSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIESgSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindIECidrSgIcmpRulesHandler := connect.NewUnaryHandler(
		SecGroupServiceFindIECidrSgIcmpRulesProcedure,
		svc.FindIECidrSgIcmpRules,
		connect.WithSchema(secGroupServiceMethods.ByName("FindIECidrSgIcmpRules")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceGetSecGroupForAddressHandler := connect.NewUnaryHandler(
		SecGroupServiceGetSecGroupForAddressProcedure,
		svc.GetSecGroupForAddress,
		connect.WithSchema(secGroupServiceMethods.ByName("GetSecGroupForAddress")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceFindHostsHandler := connect.NewUnaryHandler(
		SecGroupServiceFindHostsProcedure,
		svc.FindHosts,
		connect.WithSchema(secGroupServiceMethods.ByName("FindHosts")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceRegisterHostHandler := connect.NewUnaryHandler(
		SecGroupServiceRegisterHostProcedure,
		svc.RegisterHost,
		connect.WithSchema(secGroupServiceMethods.ByName("RegisterHost")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceUpdateHostIPsetHandler := connect.NewUnaryHandler(
		SecGroupServiceUpdateHostIPsetProcedure,
		svc.UpdateHostIPset,
		connect.WithSchema(secGroupServiceMethods.ByName("UpdateHostIPset")),
		connect.WithHandlerOptions(opts...),
	)
	secGroupServiceDeleteHostHandler := connect.NewUnaryHandler(
		SecGroupServiceDeleteHostProcedure,
		svc.DeleteHost,
		connect.WithSchema(secGroupServiceMethods.ByName("DeleteHost")),
		connect.WithHandlerOptions(opts...),
	)
	return "/hbf.v2.sgroups.SecGroupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecGroupServiceSyncProcedure:
			secGroupServiceSyncHandler.ServeHTTP(w, r)
		case SecGroupServiceSyncStatusProcedure:
			secGroupServiceSyncStatusHandler.ServeHTTP(w, r)
		case SecGroupServiceSyncStatusesProcedure:
			secGroupServiceSyncStatusesHandler.ServeHTTP(w, r)
		case SecGroupServiceListNetworksProcedure:
			secGroupServiceListNetworksHandler.ServeHTTP(w, r)
		case SecGroupServiceListSecurityGroupsProcedure:
			secGroupServiceListSecurityGroupsHandler.ServeHTTP(w, r)
		case SecGroupServiceGetSgSubnetsProcedure:
			secGroupServiceGetSgSubnetsHandler.ServeHTTP(w, r)
		case SecGroupServiceFindSgSgRulesProcedure:
			secGroupServiceFindSgSgRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindFqdnRulesProcedure:
			secGroupServiceFindFqdnRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindSgIcmpRulesProcedure:
			secGroupServiceFindSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindSgSgIcmpRulesProcedure:
			secGroupServiceFindSgSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIECidrSgRulesProcedure:
			secGroupServiceFindIECidrSgRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIESgSgRulesProcedure:
			secGroupServiceFindIESgSgRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIESgSgIcmpRulesProcedure:
			secGroupServiceFindIESgSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceFindIECidrSgIcmpRulesProcedure:
			secGroupServiceFindIECidrSgIcmpRulesHandler.ServeHTTP(w, r)
		case SecGroupServiceGetSecGroupForAddressProcedure:
			secGroupServiceGetSecGroupForAddressHandler.ServeHTTP(w, r)
		case SecGroupServiceFindHostsProcedure:
			secGroupServiceFindHostsHandler.ServeHTTP(w, r)
		case SecGroupServiceRegisterHostProcedure:
			secGroupServiceRegisterHostHandler.ServeHTTP(w, r)
		case SecGroupServiceUpdateHostIPsetProcedure:
			secGroupServiceUpdateHostIPsetHandler.ServeHTTP(w, r)
		case SecGroupServiceDeleteHostProcedure:
			secGroupServiceDeleteHostHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecGroupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecGroupServiceHandler struct{}

func (UnimplementedSecGroupServiceHandler) Sync(context.Context, *connect.Request[sgroups.SyncReq]) (*connect.Response[empty.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.Sync is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) SyncStatus(context.Context, *connect.Request[empty.Empty]) (*connect.Response[sgroups.SyncStatusResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.SyncStatus is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) SyncStatuses(context.Context, *connect.Request[empty.Empty], *connect.ServerStream[sgroups.SyncStatusResp]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.SyncStatuses is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListNetworks(context.Context, *connect.Request[sgroups.ListNetworksReq]) (*connect.Response[sgroups.ListNetworksResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.ListNetworks is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) ListSecurityGroups(context.Context, *connect.Request[sgroups.ListSecurityGroupsReq]) (*connect.Response[sgroups.ListSecurityGroupsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.ListSecurityGroups is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) GetSgSubnets(context.Context, *connect.Request[sgroups.GetSgSubnetsReq]) (*connect.Response[sgroups.GetSgSubnetsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.GetSgSubnets is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindSgSgRules(context.Context, *connect.Request[sgroups.FindSgSgRulesReq]) (*connect.Response[sgroups.SgSgRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindSgSgRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindFqdnRules(context.Context, *connect.Request[sgroups.FindFqdnRulesReq]) (*connect.Response[sgroups.FqdnRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindFqdnRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindSgIcmpRules(context.Context, *connect.Request[sgroups.FindSgIcmpRulesReq]) (*connect.Response[sgroups.SgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindSgSgIcmpRules(context.Context, *connect.Request[sgroups.FindSgSgIcmpRulesReq]) (*connect.Response[sgroups.SgSgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindSgSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIECidrSgRules(context.Context, *connect.Request[sgroups.FindIECidrSgRulesReq]) (*connect.Response[sgroups.IECidrSgRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindIECidrSgRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIESgSgRules(context.Context, *connect.Request[sgroups.FindIESgSgRulesReq]) (*connect.Response[sgroups.IESgSgRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindIESgSgRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIESgSgIcmpRules(context.Context, *connect.Request[sgroups.FindIESgSgIcmpRulesReq]) (*connect.Response[sgroups.IESgSgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindIESgSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindIECidrSgIcmpRules(context.Context, *connect.Request[sgroups.FindIECidrSgIcmpRulesReq]) (*connect.Response[sgroups.IECidrSgIcmpRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindIECidrSgIcmpRules is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) GetSecGroupForAddress(context.Context, *connect.Request[sgroups.GetSecGroupForAddressReq]) (*connect.Response[sgroups.SecGroup], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.GetSecGroupForAddress is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) FindHosts(context.Context, *connect.Request[sgroups.FindHostsReq]) (*connect.Response[sgroups.HostList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.FindHosts is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) RegisterHost(context.Context, *connect.Request[sgroups.RegisterHostReq]) (*connect.Response[empty.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.RegisterHost is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) UpdateHostIPset(context.Context, *connect.Request[sgroups.UpdateHostIPReq]) (*connect.Response[empty.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.UpdateHostIPset is not implemented"))
}

func (UnimplementedSecGroupServiceHandler) DeleteHost(context.Context, *connect.Request[sgroups.DeleteHostReq]) (*connect.Response[empty.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hbf.v2.sgroups.SecGroupService.DeleteHost is not implemented"))
}
